/**
 * 
 * @author Djoumbou Feunang, Yannick, PhD
 *
 */

package biotransformer.transformation;

//import biotransformer.transformation.MetabolicReaction.*;


public class MRPatterns {

//	public static void main(String[] args){
//		System.out.println(MReactionSets.standardizationReactions.size());
//	}

	public MRPatterns() {
		// TODO Auto-generated constructor stub
	}


	public enum ReactionName {

		/**
		 * 	Standardization reactions
		 */
//		AZIDE_STANDARDIZATION, DIAZO_STANDARDIZATION, DIAZONIUM_STANDARDIZATION,
//		IMINIUM_STANDARDIZATION, ISOCYANATE_STANDARDIZATION, NITRILIUM_STANDARDIZATION,
//		NITRO_STANDARDIZATION, NITRO_STANDARDIZATION_1, NITRONATE_STANDARDIZATION,
//		NITROSO_STANDARDIZATION, PHOSPHONIC_STANDARDIZATION, PHOSPHORIC_STANDARDIZATION,
//		PHOSPHORIC_STANDARDIZATION_2, PHOSPHONIUM_YLIDE_STANDARDIZATION,
//		SELENITE_STANDARDIZATION, SILICATE_STANDARDIZATION, SULFINE_STANDARDIZATION,
//		SULFONE_STANDARDIZATION, SULFONIUM_YLIDE_STANDARDIZATION, SULFOXIDE_STANDARDIZATION,
//		SULFOXONIUM_YLIDE_STANDARDIZATION, TERTIARY_N_OXIDE_STANDARDIZATION, THIOUREA_STANDARDIZATION,
//		CARBAMIDOTHIOIC_ACID_TO_THIOUREA_STANDARDIZATION, CARBAMIDIC_ACID_TO_UREA_STANDARDIZATION,
//		CARBOXYLIC_ACID_ANION_STANDARDIZATION,SULFONIC_ACID_STANDARDIZATION,
//		COENZYME_A_STANDARDIZATION,ANTHOCYANIDIN_STANDARDIZATION_PATTERN1,
//		CARBOXAMIDE_STANDARDIZATION_PATTERN1, CARBOXAMIDE_STANDARDIZATION_PATTERN2,


//		/**
//		 * CYP450 reactions
//		 */
//		AROMATIC_HYDROXYLATION_PATTERN2, AROMATIC_HYDROXYLATION_PATTERN3,
//		PRIMARY_ARYLAMIDE_N_HYDROXYLATION, SECONDARY_ARYLAMIDE_N_HYDROXYLATION,
//		SECONDARY_N_DEALKYLATION, TERTIARY_N_DEALKYLATION,
//		HYDROXYLATION_OF_METHYL_CARBON_ADJACENT_TO_ALIPHATIC_RING,
//		HYDROXYLATION_OF_TERMINAL_METHYL_PATTERN1, HYDROXYLATION_OF_TERMINAL_METHYL_PATTERN2,
//		S_OXIDATION_OF_DIARYLTHIOETHER_TO_SULFOXIDE, AROMATIC_ALDEHYDE_REDUCTION,
//		PRIMARY_AMINE_HYDROXYLATION_PATTERN1, PRIMARY_AMINE_HYDROXYLATION_PATTERN2,
//		SECONDARY_AMINE_HYDROXYLATION_PATTERN1, SECONDARY_AMINE_HYDROXYLATION_PATTERN2, SECONDARY_AMINE_HYDROXYLATION_PATTERN3,
//		AMINE_N_OXIDATION, HYDROXYLATION_OF_METHYL_ARYL_OR_VINYL_CARBON, ALLYLIC_HYDROXYLATION_PATTERN1, ALLYLIC_HYDROXYLATION_PATTERN2,
//		ALLYLIC_HYDROXYLATION_PATTERN3, THIOPHENE_23_EPOXIDATION, OXIDATIVE_DEAMINATION, NITROIMINE_REDUCTION,
//		TERTIARY_AMINE_N_HYDROXYLATION_PATTERN1, TERTIARY_AMINE_N_HYDROXYLATION_PATTERN2,
//		CYP_NADH_TERTIARY_AMINE_C_HYDROXYLATION, QUATERNARY_N_DEALKYLATION, S_DEALKYLATION, DESULPHURIZATION_OF_PHOSPHOR,
//		KETONE_REDUCTION, ISOMERIZATION_OF_ALKYLARENE_OXIDE_TO_PHENOL, FURAN_23_EPOXIDATION, FURAN_23_EPOXIDATION_2,
//		_13_THIAZOLE_45_EPOXIDATION, _13_THIAZOLE_45_EPOXIDATION_2, N_OXIDATION_OF_IMINE, N_OXIDATION_OF_HYDRAZINE,
//		S_OXIDATION_OF_THIOCARBAMIDE_PATTERN1, S_OXIDATION_OF_THIOCARBAMIDE_PATTERN2, S_OXIDATION_OF_THIOCARBAMIDE_PATTERN3,
//		S_OXIDATION_OF_THIOCARBAMIDE_PATTERN4, S_OXIDATION_OF_THIOAMIDE, AZOREDUCTION_TO_PRIMARY_AMINE, NITRO_REDUCTION_TO_HYDROXYLAMINE,
//		NITRO_REDUCTION_TO_OXIME, ALIPHATIC_REDUCTIVE_DEHALOGENATION, DIHALO_ELIMINATION, DEHYDROHALOGENATION,
//		REDUCTIVE_DEHALOGENATION_OF_ARYL_HALIDE, SULFONE_REDUCTION_TO_SULFOXIDE, SULFOXIDE_REDUCTION_TO_THIOETHER_PATTERN1,
//		SULFOXIDE_REDUCTION_TO_THIOETHER_PATTERN2, ALIPHATIC_HYDROXYLATION, O_DEBENZYLATION, DESULFURATION, IMIDAZOLIDINE_OXIDATION,
//		OXIDATION_OF_4_SUBSTITUTTED_PHENOL_PATTERN1,OXIDATION_OF_4_SUBSTITUTTED_PHENOL_PATTERN2,OXIDATION_OF_P_SUBSTITUTED_ANILIDES,
//		_2_ELECTRON_OXIDATION_OF_O_AMINOPHENOLS_TO_QUINONE_IMINES_PATTERN1,_2_ELECTRON_OXIDATION_OF_O_AMINOPHENOLS_TO_QUINONE_IMINES_PATTERN2,
//		_2_ELECTRON_OXIDATION_OF_P_AMINOPHENOLS_TO_QUINONE_IMINES_PATTERN1, _2_ELECTRON_OXIDATION_OF_P_AMINOPHENOLS_TO_QUINONE_IMINES_PATTERN2,
//		OXIDATION_OF_4_SUBSTITUTED_PHENOLS_TO_P_QUINONE_METHIDES_PATTERN1,OXIDATION_OF_2_SUBSTITUTED_PHENOLS_TO_O_QUINONE_METHIDES_PATTERN1,
//		OXIDATION_OF_2_SUBSTITUTED_PHENOLS_TO_O_QUINONE_METHIDES_PATTERN2, OXIDATION_OF_4_SUBSTITUTED_BENZENE_PATTERN1,
//		OXIDATION_OF_4_SUBSTITUTED_BENZENE_PATTERN2, OXIDATION_OF_4_SUBSTITUTED_BENZENE_PATTERN3,
//		OXIDATION_OF_4_SUBSTITUTED_BENZENE_PATTERN4, OXIDATION_OF_METHYL_TO_CARBOXYLIC_ACID, EPOXIDATION, FURAN_EPOXIDATION,
//		THIOPHENE_EPOXIDATION, ARENE_EPOXIDATION_PATTERN1, ARENE_EPOXIDATION_PATTERN2, AROMATIC_HYDROXYLATION_OF_FUSED_BENZENE_RING_PATTERN1,
//		AROMATIC_HYDROXYLATION_OF_FUSED_BENZENE_RING_PATTERN2, AROMATIC_HYDROXYLATION_OF_FUSED_BENZENE_RING_PATTERN3,
//		AROMATIC_HYDROXYLATION_OF_FUSED_BENZENE_RING_PATTERN4,
//		HYDROXYLATION_OF_AROMATIC_CARBON, _7_HYDROXYLATION_OF_COUMARINS, _3_HYDROXYLATION_OF_COUMARINS,
//		_2_HYDROXYLATION_OF_14_DISUBSTITUTED_BENZENES_PATTERN1, _2_HYDROXYLATION_OF_14_DISUBSTITUTED_BENZENES_PATTERN2,
//		_2_HYDROXYLATION_OF_14_DISUBSTITUTED_BENZENES_PATTERN3, HYDROXYLATION_OF_124_TRISUBSTITUTED_BENZENES_PATTERN1,
//		HYDROXYLATION_OF_124_TRISUBSTITUTED_BENZENES_PATTERN2, M_HYDROXYLATION_OF_MONOSUBSTITUTED_BENZENE,
//		O_HYDROXYLATION_OF_MONOSUBSTITUTED_BENZENE, P_HYDROXYLATION_OF_MONOSUBSTITUTED_BENZENE, P_HYDROXYLATION_OF_ANILIDES,
//		O_HYDROXYLATION_OF_PHENOLS, P_HYDROXYLATION_OF_PHENOLS, HYDROXYLATION_OF_AROMATIC_CARBON_META_TO_HALIDE_GROUP,
//		HYDROXYLATION_OF_AROMATIC_CARBON_ORTHO_TO_HALIDE_GROUP, HYDROXYLATION_OF_AROMATIC_CARBON_PARA_TO_HALIDE_GROUP,
//		HYDROXYLATION_OF_HETEROAROMATIC_CARBON, HYDROXYLATION_OF_AROMATIC_CARBON_ADJACENT_TO_N, HYDROXYLATION_OF_AROMATIC_CARBON_ADJACENT_TO_S,
//		HYDROXYLATION_OF_AROMATIC_CARBON_ADJACENT_TO_O, HYDROXYLATION_OF_BENZENE_ORTHO_TO_EDG, HYDROXYLATION_OF_BENZENE_ORTHO_TO_STRONGLY_EDG,
//		HYDROXYLATION_OF_BENZENE_PARA_TO_EDG, HYDROXYLATION_OF_BENZENE_PARA_TO_STRONGLY_EDG, HYDROXYLATION_OF_BENZENE_META_TO_EWG,
//		HYDROXYLATION_OF_BENZENE_META_TO_STRONGLY_EWG, DIHYDROXYLATION_OF_DOUBLE_BOND, ALKYL_HYDROXYLATION, _4_ALKYL_HYDROXYLATION_OF_OXOAZAPHOSPHORINE,
//		ALIPHATIC_HYDROXYLATION_OF_ACYCLIC_12_DISUBSTITUTED_ALKENE_PATTERN1, ALPHA_HYDROXYLATION_OF_CARBONYL_GROUP, HYDROXYLATION_OF_CARBON_ALPHA_TO_CONJUGATED_CARBONYL,
//		HYDROXYLATION_OF_CARBON_BETA_TO_CONJUGATED_CARBONYL, HYDROXYLATION_OF_CARBON_GAMMA_TO_CONJUGATED_CARBONYL,
//		ALIPHATIC_HYDROXYLATION_OF_METHYL_CARBON_ADJACENT_TO_AROMATIC_RING, ALIPHATIC_HYDROXYLATION_OF_METHYL_CARBON_ADJACENT_TO_VINYL_GROUP,
//		ALIPHATIC_HYDROXYLATION_OF_METHYL_CARBON_ADJACENT_TO_ALKYNE_GROUP, HYDROXYLATION_OF_TERMINAL_METHYL,
//		HYDROXYLATION_OF_METHYL_FROM_N_METHYLCARBAMATE, HYDROXYLATION_OF_ACYCLIC_ALIPHATIC_SECONDARY_CARBON,
//		HYDROXYLATION_OF_ALIPHATIC_SECONDARY_CARBON, HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON_PATTERN1,
//		HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON_PATTERN2, HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON_PATTERN3,
//		HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON_PATTERN4, HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON_PATTERN5,
//		HYDROXYLATION_OF_SECONDARY_HETEROALICYCLIC_CARBON_PATTERN1, HYDROXYLATION_OF_SECONDARY_HETEROALICYCLIC_CARBON_PATTERN2,
//		HYDROXYLATION_OF_ALIPHATIC_SECONDARY_PENULTIMATE_CARBON, HYDROXYLATION_OF_ALIPHATIC_TERTIARY_PENULTIMATE_CARBON,
//		HYDROXYLATION_OF_ALIPHATIC_SECONDARY_ANTEPENULTIMATE_CARBON_PATTERN1, HYDROXYLATION_OF_ALIPHATIC_TERTIARY_ANTEPENULTIMATE_CARBON,
//		HYDROXYLATION_OF_ALIPHATIC_PENULTIMATE_CARBON_ADJACENT_TO_AROMATIC_CARBON, HYDROXYLATION_OF_ALIPHATIC_NON_TERMINAL_CARBON_ADJACENT_TO_AROMATIC_RING,
//		HYDROXYLATION_OF_ARYL_METHINE, HYDROXYLATION_OF_ALKYL_METHINE, METHYLENE_HYDROXYLATION, ALIPHATIC_HYDROXYLATION_OF_CARBON_ADJACENT_TO_HALOGEN_GROUP,
//		ALIPHATIC_HYDROXYLATION_OF_CARBON_ALPHA_TO_PRIMARY_ALKYL_N, ALIPHATIC_HYDROXYLATION_OF_CARBON_ALPHA_TO_SECONDARY_OR_TERTIARY_ALKYL_N,
//		_3_HYDROXYLATION_OF_5_ARYL_14_BENZODIAZEPINES, ALIPHATIC_HYDROXYLATION_OF_CARBON_ADJACENT_TO_OXYGEN, ALIPHATIC_HYDROXYLATION_OF_CARBON_ADJACENT_TO_SULFUR,
//		ALIPHATIC_HYDROXYLATION_OF_ALPLHA_CARBON_IN_ARYL_OR_VINYL_ETHER, HYDROXYLATION_OF_ALPHA_CARBON_IN_DIALKYLETHERS, HYDROXYLATION_OF_SP3_ADJACENT_TO_N_IN_NITROSAMINES,
//		OXIDATION_OF_TERMINAL_ACETYLENES, OXIDATION_OF_DISUBSTITUTED_ARYL_ACETYLENES, HYDROXYLATION_OF_C_NEXT_TO_AMIDES, NITROSODIALKYLAMINE_ALPHA_HYDROXYLATION,
//		ALLYLIC_HYDROXLATION, BISALLYLIC_HYDROXYLATION, OXIDATION_OF_ALPHA_CARBON_N_IN_SUBSTITUTED_MORPHOLINE, ALDEHYDE_OXIDATION, ARYL_ALDEHYDE_OXIDATION,
//		OXIDATION_OF_PRIM_ALCOHOL_TO_ALDEHYDE, OXIDATION_OF_PRIM_ALCOHOL_TO_CARBOXYLIC_ACID, OXIDATION_OF_SEC_ALCOHOL_TO_KETONE, N_HYDROXYLATION_OF_MONOALKYLAMINES,
//		N_HYDROXYLATION_OF_PRIMARY_ARYLAMINE, HYDROXYLATION_OF_PRIMARY_AMINO_AZAHETEROCYCLIC_NITROGEN, N_HYDROXYLATION_OF_PRIM_SEC_ALIPHATIC_AMINES,
//		N_HYDROXYLATION_OF_SECONDARY_ARYLAMINE, N_HYDROXYLATION_OF_SECONDARY_ALICYCLIC_AMINE, HYDROXYLATION_OF_ACYCLIC_TERTIARY_AMINE, N_OXIDATION_OF_ALICYCLIC_TERTIARY_AMINE,
//		N_OXIDATION_OF_ALIPHATIC_TERTIARY_AMINE_PATTERN1, N_OXIDATION_OF_ALIPHATIC_TERTIARY_AMINE_PATTERN2, N_HYDROXYLATION_OF_TERTIARY_ARYLAMINE_PATTERN1,
//		N_HYDROXYLATION_OF_TERTIARY_ARYLAMINE_PATTERN2, N_HYDROXYLATION_OF_ARYL_OR_VINYL_AMINE, N_HYDROXYLATION_OF_ANILINES_TO_HYDROXYLAMINES,
//		N_HYDROXYLATION_OF_SECONDARY_ARYLAMIDES, N_HYDROXYLATION_OF_ANILIDES, OXIDATION_OF_ALKYL_FORMAMIDES, OXIDATION_OF_ARYL_FORMAMIDES,
//		N_OXIDATION_OF_P_SUBSTITUTED_NN_DIALKYLANILINE, N_OXIDATION_OF_HYDRAZINES, N_HYDROXYLATION_OF_NN_DISUBSTITUTED_HYDROXYLAMINE,
//		N_OXIDATION_OF_AZO_GROUPS, N_HYDROXYLATION_OF_IMINES_PATTERN1, N_HYDROXYLATION_OF_IMINES_PATTERN2, N_HYDROXYLATION_OF_CARBOXAMIDINES,
//		N_HYDROXYLATION_OF_GUANIDINES_AND_AMINOHYDROAZONES, AROMATIC_N_OXIDATION, PYRIDINE_N_OXIDATION, N_OXIDATION_OF_PYRIMIDINE_RING, OXIDATION_OF_N_IN_STRAINED_RING_SYSTEMS,
//		OXIDATION_OF_ARYLHYDRAZINE_PATTERN1, OXIDATION_OF_ARYLHYDRAZINE_PATTERN2, S_HYDROXYLATION_OF_ALKYLTHIOETHERS, OXIDATION_OF_ALICYCLIC_S_TO_SULFOXIDE,
//		S_OXIDATION_OF_ALIPHATIC_SULFHYDRYL_TO_SULFENIC_ACID, S_OXIDATION_OF_ARYL_OR_VINYL_SULFHYDRYL_TO_SULFENIC_ACID, OXIDATION_OF_THIOUREAS, S_OXIDATION_OF_ORGANOSULFUROUS_COMPOUNDS,
//		S_OXIDATION_OF_DITHIOCARBAMATE, S_OXIDATION_OF_THIOCARBAMATE, S_OXIDATION_OF_DIALKYLTHIOETHER_TO_SULFOXIDE, S_OXIDATION_OF_ALKYLARYLTHIOETHER_TO_SULFOXIDE,
//		S_OXIDATION_OF_SULFOXIDE_TO_SULFONE, OXIDATION_OF_S_ADJACENT_TO_ALIPHATIC_NITROGENS, THIOPHENE_S_OXIDATION, THIONO_OXIDATION, PHOSPHINE_OXIDATION, O_DEALKYLATION,
//		O_DEALKYLATION_OF_DIALKYLETHER, O_DEISOPROPYLATION, O_ARYL_DEALKYLATION_ADJACENT_TO_SUBSTITUTED_CARBON, O_ARYL_DEALKYLATION_NOT_ADJACENT_TO_SUBSTITUTED_CARBON,
//		_4P_O_DEMETHYLATION_OF_FLAVONE, O_ARYL_DEMETHYLATION_PATTERN1, N_DEALKYLATION_OF_UREAS, N_DEALKYLATION_OF_SULFONYLUREAS, N_DEALKYLATION_OF_SULFONAMIDES,
//		N_DEALKYLATION_OF_SECONDARY_CARBOXAMIDES, N_DEALKYLATION_OF_TERTIARY_CARBOXAMIDES, N_DEALKYLATION_OF_TERTIARY_CARBOXAMIDES_PATTERN2,
//		N_DEALKYLATION_OF_ACYCLIC_SECONDARY_AMINES, N_DEALKYLATION_OF_SECONDARY_ARYLALKYL_AMINES, N_DEALKYLATION_OF_ACYCLIC_TERTIARY_AMINES,
//		N_DEALKYLATION_OF_ALIPHATIC_TERTIARY_AMINES_PATTERN1, N_DEALKYLATION_OF_ALICYCLIC_TERTIARY_AMINES_PATTERN1, N_DEALKYLATION_OF_MIXED_TERTIARY_AMINES,
//		N_DEALKYLATION_OF_N_ALKYLNITROSAMINE, N_DEALKYLATION_OF_DICARBOXIMIDE, N_DEALKYLATION_OF_N_ACYLUREAS_PATTERN1, N_DEALKYLATION_OF_N_ACYLUREAS_PATTERN2,
//		N_DEALKYLATION_OF_HYDRAZINE, N_DEALKYLATION_OF_NN_DIALKYLANILINE, N_DEALKYLATION_OF_NITROSODIALKYLAMINES, N_DEPROPARGYLATION_OF_SEC_AND_TERT_AMINES,
//		N_DEISOPROPYLATION, N_DEALKOXYLATION, N_DEALKOXYLATION_OF_N_ARYL_N_CHLOROACETAMIDES, N_DECHLOROETHYLATION, N_DEMETHOXYMETHYLATION, S_DEALKYLATION_OF_ALKYLTHIOETHERS,
//		S_DEMETHYLATION_OF_SULFUR_ADJACENT_TO_AROMATIC_RING, OXIDATIVE_DEARYLATION, DESULFURATION_OF_ORGANOPHOSPHOROTHIOATES, DESULFURATION_OF_ORGANOPHOSPHORODITHIOATES,
//		DESULFURATION_OF_ORGANOISOTHIOCYANATE, ALIPHATIC_HYDROLYTIC_DEHALOGENATION, HYDROLYTIC_DEHALOGENATION_OF_ARYL_HALIDE, OXIDATION_OF_HALOTRIFLUOROETHANE_PATTERN1,
//		OXIDATION_OF_HALOTRIFLUOROETHANE_PATTERN2, OXIDATION_OF_HALOTRIFLUOROETHANE_PATTERN3, REDUCTION_OF_HALOTRIFLUOROETHANE_PATTERN1,
//		REDUCTION_OF_HALOTRIFLUOROETHANE_PATTERN2, REDUCTION_OF_HALOTRIFLUOROETHANE_PATTERN3, REDUCTION_OF_TERMINAL_ALIPHATIC_TRIHALIDES,
//		HYDROXY_REPLACEMENT_OF_ACTIVATED_ALPHA_CARBONYL_HALIDE, DEARYLATION_OF_ORGANOPHOSPHOSULFUR_COMPOUNDS_PATTERN1, DEARYLATION_OF_ORGANOPHOSPHOSULFUR_COMPOUNDS_PATTERN2,
//		REDUCTION_OF_KETONE_TO_ALCOHOL, REDUCTION_OF_ALDEHYDES_TO_ALCOHOL, REDUCTION_OF_NITROIMINES, REDUCTION_OF_NITRO_TO_AMINE, REDUCTION_OF_NITRO_TO_HYDROXYLAMINE,
//		REDUCTION_OF_NITRO_TO_NITROSO, REDUCTION_OF_AMIDOXIMES, METHYLENEDIOXY_RING_OPENING, _2_AROYL_THIOPHENE_45_EPOXIDE_RING_OPENING, OXAZOLE_RING_OPENING,
//		_24_THIAZOLIDINEDIONE_RING_OPENING_PATTERN1, _24_THIAZOLIDINEDIONE_RING_OPENING_PATTERN2, RING_OPENING_OF_MONO_N_SUBSTITUTED_PIPERAZINE,
//		RING_OPENING_OF_DI_N_SUBSTITUTED_PIPERAZINE_PATTERN1, RING_OPENING_OF_DI_N_SUBSTITUTED_PIPERAZINE_PATTERN2, RING_OPENING_OF_N_SUBSTITUTED_MORPHOLINE,
//		CYCLOGUANIDE_FORMATION, FORMATION_OF_IMMINIUM_ION_FROM_DI_N_SUBSTITUTED_PIPERAZINE, FORMATION_OF_PYRIDINIUM_FROM_4_SUBSTITUTED_PIPERIDINE,
//		FORMATION_OF_IMMINIUM_ION_FROM_N_SUBSTITUTED_PIPERIDINE, RING_OPENING_OF_N_SUBSTITUTED_PIPERIDINE_RING, FORMATION_OF_IMINIUM_IN_PYRROLIDINE_RING,
//		TERMINAL_DESATURATION, N_DEHYDROGENATION_OF_ALIPHATIC_AZAHETEROCYCLE_PATTERN1, N_DEHYDROGENATION_OF_ALIPHATIC_AZAHETEROCYCLE_PATTERN2,
//		DEHYDROGENATION_OF_ALPHA_BETA_UNSATURATED_AMIDE, DEHYDROGENATION_OF_ALPHA_BETA_UNSATURATED_ALDEHYDE_CARBOXYLIC_ACID_OR_ESTER,
//		DEHYDROGENATION_OF_FUSED_PYRROLIDINES, DEHYDROGENATION_OF_4_ARYL_SUBSTITUTED_14_DIHYDROPYRIDINES, DEHYDROGENATION_OF_4_ALKYL_SUBSTITUTED_14_DIHYDROPYRIDINES,
//		DEHYDDROGENATION_OF_PYRROLIZIDINE_ALKALOIDS, HYDROLYSIS_OF_N_ACYL_UREA, CLEAVAGE_OF_THIOCARBAMATE, DENITROSATION, NITROSODIALKYLAMINE_DENITROSATION,
//		NS_CLEAVAGE, HYDROLYSIS_OF_CARBOXYLIC_ACID_AMIDE, REDUCTION_OF_DISULFIDE, OXIDATIVE_DEAMINATION_OF_PRIMARY_AMINES, OXIDATIVE_DEAMINATION_OF_TERTIARY_AMINES,
//		DESTHIOPROPYLATION, REDUCTION_OF_AZO_GROUPS, DESULFURIZATION_OF_THIOAMIDE_INTO_AMIDE, HYDROXYLATION_OF_HETEROALICYCLIC_CARBON_NEAR_DOUBLY_BONDED_NITROGEN,
//		EPOXIDATION_OF_MONOSUBSTITUTED_ALKENE, N_DEALKYLATION_OF_HYDRAZIDE, ALLYLIC_HYDROXYLATION, HYDROLYSIS_OF_CARBOXYLIC_ESTER, TERMINAL_DESATURATION_PATTERN1,
//		HYDROXYLATION_OF_ALICYCLIC_SECONDARY_CARBON, EPOXIDATION_OF_VINYL_ETHER, N_DEALKYLATION_OF_TERTIARY_AMINE_IN_AROMATIC_RING,
//		ALIPHATIC_HYDROXYLATION_OF_ENDOCYCLIC_CARBON, HYDROLYSIS_OF_ESTER, N_DEALKYLATION_OF_CYCLIC_TERTIARY_AMINES, HYDROXYLATION_OF_ACYCLIC_SECONDARY_CARBON,
//		_2E_OXIDATION_OF_AMINOPHENOLS, ALIPHATIC_HYDROXYLATION_AT_PENULTIMATE_CARBON_ADJACENT_TO_AROMATIC_CARBON, N_DEALKYLATION_UF_UREAS,
//		ALKENE_EPOXIDATION_PATTERN1,ALKENE_EPOXIDATION_PATTERN2, ALKENE_HYDROXYLATION, OXIDATIVE_DEBORONATION, N_DEALKYLATION_OF_PHOSPHORAMIDE_PATTERN1,
//		N_DEALKYLATION_OF_PHOSPHORAMIDE_PATTERN2, DEHYDROGENATION_OF_PRIMARY_ALCOHOL_PATTERN1, DEHYDROGENATION_OF_PRIMARY_ALCOHOL_PATTERN2,
//		DEHYDROGENATION_OF_SECONDARY_ALCOHOL_PATTERN1, DEHYDROGENATION_OF_SECONDARY_ALCOHOL_PATTERN2, CARBONYL_REDUCTION, _2E_REDUCTION_OF_NITROGUANIDINE,
//		_6E_REDUCTION_OF_NITROGUANIDINE, _2E_REDUCTION_OF_NITROMETHYLENE, _4P_HYDROXYLATION_OF_OXAZAPHOSPHORINE, OXIDATION_OF_4_HYDROXYAZAPHOSPHORINE,
//		HYDROXYLATION_OF_ALICYCLIC_TERTIARY_CARBON, N_METHYL_HYDROXYLATION_OF_CARBAMATE, HYDROLYSIS_OF_O_ARYL_CARBAMATE,
//		ALPHA_HYDROXYLATION_OF_ARYLDIMETHYLUREA, N_DEMETHYLATION_OF_ARYLDIMETHYLUREA, N_DEMETHYLATION_OF_ARYLDIMETHYLAMINE,
//		ALPHA_HYDROXYLATION_OF_ARYLDIMETHYLAMINE, ALPHA_HYDROXYLATION_OF_ARYLDIMETHYLFORMAMIDINE, N_DEMETHYLATION_OF_ARYLDIMETHYLFORMAMIDINE,
//		ALPHA_HYDROXYLATION_OF_ARYLDIMETHYLAMINE_PATTERN1, ALPHA_HYDROXYLATION_OF_ARYLDIMETHYLAMINE_PATTERN2, N_DEMETHYLATION_OF_ARYLDIMETHYLAMINE_PATTERN1,
//		N_DEMETHYLATION_OF_ARYLDIMETHYLAMINE_PATTERN2, PHENOLIC_ACID_DECARBOXYLATION, AROMATIC_L_AMINO_ACID_DECARBOXYLATION, _4_O_SULFATION_OF_HYDROXYCINNAMATE_PATTERN1,
//		_4_O_SULFATION_OF_HYDROXYCINNAMATE_PATTERN2,
//		REDUCTION_OF_ALPHA_BETA_CARBON_DOUBLE_BOND_ADJACENT_TO_EWG_PATTERN1,
//		REDUCTION_OF_ALPHA_BETA_CARBON_DOUBLE_BOND_ADJACENT_TO_EWG_PATTERN2,
//		REDUCTION_OF_ALPHA_BETA_CARBON_DOUBLE_BOND_ADJACENT_TO_EWG_PATTERN3,
//
////		PYRROLE_EPOXIDATION,
//
//		/**
//		 * 	Phase II reactions
//		 */
//
//		// This is the preferred route of conjugating aromatic amines (R-NH2, converted to aromatic amides
//		// R-NH-COCH3) and hydrazines (R-NH-NH2, converted to R-NH-NH-COCH3
//		// http://www.reactome.org/PathwayBrowser/#R-HSA-156582&FLG=P18440
//
//		ARYLAMINE_N_ACETYLATION_PATTERN1, ARYLAMINE_N_ACETYLATION_PATTERN2, ARYLAMINE_N_ACETYLATION_PATTERN3,
//		N_ARYLHYDROXYLAMINE_O_ACETYLATION, N_ACETYLATION_OF_PRIMARY_AMINE,
//		N_ACETYLATION_OF_HYDRAZINE_DERIVATIVE, N_ACETYLATION_OF_SULFONAMIDE,
//		PHENOLIC_STEROID_SULFONATION, N_ARYLHYDROXYLAMINE_O_SULFONATION,
//		SULFONATION_OF_HYDROXYLAMINE, _3_O_SULFATION_OF_PHENOLIC_COMPOUND, _4_O_SULFATION_OF_PHENOLIC_COMPOUND,
//		SULFONATION_OF_ALIPHATIC_ALCOHOL, PRIMARY_AMINE_N_SULFONATION, SECONDARY_AMINE_N_SULFONATION,
//		TERTIARY_AMINE_N_SULFONATION, CARBAMATE_SULFONATION, O_SULFONATION_OF_VINYL_ALCOHOL,
//		O_SULFONATION_OF_AROMATIC_ALCOHOL, PHENOL_O_SULFONATION,
//		GLYCINATION_OF_ALIPHATIC_ACID, GLYCINATION_OF_ARYL_ACID, C24_BILE_ACID_COA_GLYCINATION_PATTERN1,
//		C23_BILE_ACID_COA_GLYCINATION_PATTERN2, GLUTAMATION_OF_ALIPHATIC_ACID, GLUTAMATION_OF_BENZYLIC_ACID,
//		AROMATIC_O_METHYLATION, CATECHOL_O_METHYLATION_PATTERN1, CATECHOL_O_METHYLATION_PATTERN2,
//		CATECHOL_O_METHYLATION_PATTERN3, THIOETHER_S_METHYLATION, THIOL_S_METHYLATION,
//		ISOFLAVONE_4P_O_METHYLATION, ARSENITE_O_METHYLATION, METHYLARSONITE_O_METHYLATION,
//		GSH_CONJUGATION_OF_ISOCYANATE, GSH_CONJUGATION_OF_ISOTHIOCYANATE, GSH_CONJUGATION_OF_SULFHYDRYL,
//		GSH_CONJUGATION_OF_EPOXIDE, GSH_CONJUGATION_OF_ARENE_EPOXIDE, GSH_CONJUGATION_OF_ORGANOHALIDE_PATTERN1,
//		GSH_CONJUGATION_OF_ORGANOHALIDE_PATTERN2, GSH_CONJUGATION_OF_ACYL_CHLORIDE,
//		GSH_CONJUGATION_OF_CARBOXIMIDIC_ACID, GSH_CONJUGATION_OF_ALPHA_BETA_UNSATURATED_CARBONYL_PATTERN1,
//		GSH_CONJUGATION_OF_ALPHA_BETA_UNSATURATED_CARBONYL_PATTERN2, GSH_CONJUGATION_OF_SULFATE, GSH_CONJUGATION_OF_NITRILE,
//		GSH_CONJUGATION_OF_ARYL_HALIDE_PATTERN1, GSH_CONJUGATION_OF_ARYL_HALIDE_PATTERN2,
//		GSH_CONJUGATION_OF_ARYL_HALIDE_PATTERN3, GSH_CONJUGATION_OF_QUINONE_PATTERN1, GSH_CONJUGATION_OF_QUINONE_PATTERN2,
//		GSH_CONJUGATION_OF_ORGANODISULFIDE, GSH_CONJUGATION_OF_HALO_S_TRIAZINE, GSH_CONJUGATION_OF_EWG_SUBSTITUTED_BENZENE_PATTERN1,
//		GSH_CONJUGATION_OF_EWG_SUBSTITUTED_BENZENE_PATTERN2, GSH_CONJUGATION_OF_ALKYLARYL_PHOSPHATE_OR_PHOSPHOROTHIOATE,
//		GSH_CONJUGATION_OF_4_HYDROXYAZAPHOSPHORINE,
//
//		ALKYL_OH_GLUCURONIDATION, AROMATIC_OH_GLUCURONIDATION, ALIPHATIC_ACYL_O_GLUCURONIDATION,
//		AROMATIC_ACYL_O_GLUCURONIDATION, HYDROXYLAMINE_N_GLUCURONIDATION_PATTERN1, 
//		HYDROXYLAMINE_N_GLUCURONIDATION_PATTERN2, SULFONAMIDE_N_GLUCURONIDATION,
//		GLUCURONIDATION_OF_PRIMARY_AROMATIC_AMINE, PYRIDINE_GLUCURONIDATION, THIOL_GLUCURONIDATION,
//		THIOPHENOL_GLUCURONIDATION, _13_DICARBONYL_C_GLUCURONIDATION,
//		ISOFLAVONE_4P_OH_GLUCURONIDATION, ISOFLAVONE_7_OH_GLUCURONIDATION, _3_OH_GLUCURONIDATION_OF_STEROL,
//		 _6_OH_GLUCURONIDATION_OF_STEROL,  _17_OH_GLUCURONIDATION_OF_STEROL,
//		FLAVONOL_3O_GLUCOSYL_12_GLUCOSYL_GLUCOSYLATION, STEROL_3BETA_GLUCOSYLATION, GLUCURONIDATION_OF_AMINE_OXIDE,
//		HYDROXAMIC_O_GLUCURONIDATION, HYDROXYLAMINE_O_GLUCURONIDATION, PHENOL_O_GLUCURONIDATION,
//		QUATERNARY_N_GLUCURONIDATION_OF_IMIDAZOLE, GLUCURONIDATION_OF_ALIPHATIC_TERTIARY_AMINE,
//		AMIDE_N_GLUCURONIDATION, AZOLE_N_GLUCURONIDATION_PATTERN1, AZOLE_N_GLUCURONIDATION_PATTERN2,
//		AZOLE_N_GLUCURONIDATION_PATTERN3, AZOLE_N_GLUCURONIDATION_PATTERN4, AZOLE_N_GLUCURONIDATION_PATTERN5,
//		AZOLE_N_GLUCURONIDATION_PATTERN6,
//		CARBAMATE_N_GLUCURONIDATION, TERTIARY_ALIPHATIC_AMINE_N_GLUCURONIDATION_PATTERN1,
//		TERTIARY_ALIPHATIC_AMINE_N_GLUCURONIDATION_PATTERN2, TERTIARY_ALIPHATIC_AMINE_N_GLUCURONIDATION_PATTERN3,
//		TERTIARY_AROMATIC_AMINE_N_GLUCURONIDATION_PATTERN1, TERTIARY_AROMATIC_AMINE_N_GLUCURONIDATION_PATTERN2,
//		TERTIARY_MIXED_AMINE_N_GLUCURONIDATION_PATTERN1, TERTIARY_MIXED_AMINE_N_GLUCURONIDATION_PATTERN2,
//		GLUCURONIDATION_OF_PRIM_SEC_ALIPH_AND_BENZYLIC_ALCOHOLS, _3_OH_GLUCURONIDATION_OF_PHENOLIC_COMPOUND, THIOPURINE_S_METHYLATION,
//		STEROID_3_SULFATE_HYDROLYSIS_PATTERN1, STEROID_3_SULFATE_HYDROLYSIS_PATTERN2,
//		GLUCURONIDATION_OF_ALICYCLIC_SECONDARY_AMINE, GLUCURONIDATION_OF_SEC_DIARYL_OR_ALKYLARYLAMINE,
//
//		/**
//		 * 	Human Gut Metabolism Reactions
//		 */
//		KETO_ENOL_TAUTOMERIZATION_PATTERN1, REDUCTION_OF_ALPHA_BETA_UNSATURATED_COMPOUNDS_PATTERN1, KETO_HYDROLYSIS_PATTERN1,
//		KETO_HYDROLYSIS_PATTERN5,
//		FLAVONOID_C_RING_REDUCTION,
//
//
//		// Anna-Marja Aura; chapter 10 - Colon-Derived Microbial Metabolites of Dietary Phenolic Compounds pp 201-231
//		// The importance of the position of hydroxyl groups on the  flavonoid skeleton was addressed by Griffiths and Smith (1972b),
//		// who found out that 5-hydroxylation enhanced colonic metabolism of flavones. Apigenin (4′,5,7-trihydroxyflavone), but not
//		// 4′,7-dihydroxyflavone, underwent C-ring  fission, and likewise genistein (4′,5,7-trihydroxyisoflavone) was degraded but not
//		// daidzein (4′,7-dihydroxyisoflavone) (Griffiths and Smith 1972b). Simons et al. (2010) showed that 4′,5,7-trihydroxyflavonoids
//		// exhibited reduced absorption in the upper intestine in humans, indicating a delivery of substantial amounts of these flavonoids
//		// to the colon. These results suggest that the site of the metabolism of the 5-hydroxylated flavonoids is the colon rather than the liver.
//
//		FLAVAN_3_OL_C_RING_FISSION_PATTERN1, FLAVAN_3_OL_C_RING_FISSION_PATTERN2,
//
//		/**
//		 * After decarboxylation, the resulting aldehyde transiently is quickly oxidized to a carboxylic acid
//		 */
//		ALPHA_KETO_ACID_DECARBOXYLATION,
//
//
//		/**
//		 * Blaut, M. et al. (2003); Transformation of Flavonoids by Intestinal Microorganisms; Int. J. Vitam. Nutr. Res., 73 (2), 2003, 79–87.
//		 * The C-ring fission occurs the same way as in flavanones, but the resulting enol group is rapidly isomerized into a ketone group.
//		 * The ketone group can also be isomorized back to enol.
//		 */
//
//		FLAVANONE_C_RING_FISSION, FLAVANON_3_OL_C_RING_FISSION,
//
//		// Marín, L et al. (2009); Bioavailability of Dietary Polyphenols and Gut Microbiota Metabolism: Antimicrobial Properties;
//		// BioMed Research International; Volume 2015, Article ID 905215, 18 pages; http://dx.doi.org/10.1155/2015/905215
//		// Unlike other flavonoids that are absorbed and secreted, anthocyanins, the glycosylated versions of
//		// anthocyanidin aglycons (as cyanidin, pelargonidin, and malvidin), do not appear to undergo extensive
//		// metabolism of the parent glycosides to glucuronic, sulfo or methyl derivatives, and therefore their bioavailability is very low.
//
//
//		/*
//		 * Anthocyanidins can form a reac- tive α-diketone, which can readily decompose to phenolic acids and the corresponding aldehydes
//		 * (Keppler and Humpf 2005). However, under the mildly acidic conditions prevailing in the in vitro colon model, phenolic acids were
//		 * not detected, unless active microbiota were present (Aura et al. 2005). This suggests that both microbial and spontaneous decomposition
//		 * of anthocyanins can occur in the intes- tinal environment.
//		 */
//
//
//		ANTHOCYANIDIN_C_RING_FISSION_PATTERN3, ANTHOCYANIDIN_C_RING_FISSION_PATTERN4, ANTHOCYANIDIN_C_RING_FISSION_PATTERN5,
//
//
//		/*
//		 * Fleschhut, J. et al. Eur J Nutr (2006) 45 : 7–18; DOI 10.1007/s00394-005-0557-8.
//		 * K. Keppler, H.-U. Humpf / Bioorg. Med. Chem. 13 (2005) 5195–5205
//		 * The alpha-diketone formed upon C-ring fission of anthocyanins is very reactive and decomposes easily to phenolic acids and aldehydes
//		 */
//		_12_DIKETONE_HYDROLYSIS,
//		ISOFLAVANONE_C_RING_FISSION_PATTERN1, ISOFLAVANONE_C_RING_FISSION_PATTERN2,
//
//		/**
//		 *(R1) Landete, J.M. et al. (2011); Ellagitannins, ellagic acid and their derived metabolites: A review about source, metabolism, functions and health
//		 * Food Research International 44 (2011) 1150–1160; doi:10.1016/j.foodres.2011.04.027
//		 * states that "in the intestine EA seems to be transformed by microorganisms through lactone-ring cleavage, decarboxylation, and dehydroxylation reactions" (R1).
//		 *
//		 * Hydrolysis of ETs with acids or bases yields hexahydroxydiphenic acid (HHDP), which spontaneously lactonizes to EA. This reaction has been utilized for the detection
//		 * and quantification of ETs as EA equivalents after acid hydrolysis of food sample (R1).
//		 *
//		 * (R2) Episin, J.C. (2013); Biological Significance of Urolithins, the Gut Microbial Ellagic Acid-Derived Metabolites: The Evidence So Far;
//		 * Evidence-Based Complementary and Alternative Medicine; Volume 2013, Article ID 270418; 15 pages; http://dx.doi.org/10.1155/2013/270418
//		 *
//		 * It is observed that ellagic acid undergo lactone-ring cleavage, and subsequent decarboxylation to form urolithins. These are then dehhydroxylated reactions
//		 * to the different metabolites (R1, R2).
//		 *
//		 * (R3) Cristina Garcia-Muñoz and Fabrice Vaillant  (2014) Metabolic Fate of Ellagitannins: Implications for Health, and Research Perspectives for Innovative Functional Foods;
//		 * Critical Reviews in Food Science and Nutrition, 54:12, 1584-1598, DOI: 10.1080/10408398.2011.644643
//		 *
//		 * "In vitro ET hydrolysis releases galloyl-glucose residues and the HHDP moiety, which undergoes lactonization and spontaneous rearrangement to the stable EA" (R3).
//		 *
//		 * Unlike ETs, free EA released in the upper GI tract can be directly absorbed. Ellagic acid and direct derivatives, such as methyl and dimethyl ethers or glucuronic acid conjugates,
//		 * have been found in human plasma and urine 1 to 5 hours after inges- tion of dietary ETs, although at relatively low concentrations (R3).
//		 */
//
//
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN1, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN2,
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN3, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN4,
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN5, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN6,
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN7, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN8,
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN9, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN10,
//		HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN11, HYDROLYSIS_OF_GLYCOSYLATED_CONDENSED_GALLOYL_GROUPS_PATTERN12,
//
//		LACTONIZATION_OF_HEXAHYDROXYDIPHENOLIC_ACID, DEPSIDE_HYDROLYSIS, GALLOYL_ESTER_HYDROLYSIS,
//		DECARBOXYLATION_OF_FUSED_BENZENE, DEHYDROXYLATION_OF_DIBENZOPYRANONE_PATTERN1,
//		DEHYDROXYLATION_OF_DIBENZOPYRANONE_PATTERN2, DEHYDROXYLATION_OF_DIBENZOPYRANONE_PATTERN3,
//		DEHYDROXYLATION_OF_DIBENZOPYRANONE_PATTERN4, LACTONE_HYDROLYSIS_PATTERN1,
//		LACTONE_HYDROLYSIS_PATTERN2, LACTONE_HYDROLYSIS_PATTERN3,
//		_4_HYDROXY_5_PHENYLVALERIC_ACID_DEHYDROXIDATION, PHENYLVALEROLACTONE_FORMATION,
//		PHENYLVALEROLACTONE_TO_PHENYLVALERIC_ACID, STRUCTURAL_REARRANGEMENT_OF_ANTHOCYANIDIN_1,
//		STRUCTURAL_REARRANGEMENT_OF_ANTHOCYANIDIN_2, STRUCTURAL_REARRANGEMENT_OF_ANTHOCYANIDIN_3,
//		STRUCTURAL_REARRANGEMENT_OF_ANTHOCYANIDIN_4, BETA_OXIDATION_OF_CARBXOYLIC_ACID,
//		ALPHA_OXIDATION_OF_CARBXOYLIC_ACID, CATECHOL_DEHYDROXYLATION_PATTERN1, CATECHOL_DEHYDROXYLATION_PATTERN2,
//		RESORCINOL_M_DEHYDROXYLATION, DEMETHYLATION_OF_METHOXY_PHENYL_AND_BENZOIC_ACIDS_PATTERN1,
//		DEMETHYLATION_OF_METHOXY_PHENYL_AND_BENZOIC_ACIDS_PATTERN2, BENZOIC_ACID_DECARBOXYLATION,
//
//
//		/**
//		 * (R1) Edlin, D.A.N et al. (1998); Purification and characterization of hydroxycinnamate decarboxylase from Brettanomyces anomalus;
//		 * Enzyme and Microbial Technology; Volume 22, Issue 4, March 1998, Pages 232-239.
//		 * (R2) Peppercorn, M.A. and Goldman, P. (1971); Caffeic acid metabolism by bacteria of the human gastrointestinal tract.;
//		 * Journal of Bacteriology 108(3), pp. 996-1000.
//		 */
//		HYDROXYCINNAMIC_ACID_DECARBOXYLATION,
//
//
//		REDUCTION_OF_VINYL_HYDROXYBENZENE, ISOFLAVONE_REDUCTION_TO_ISOFLAVANONE, ISOFLAVANONE_DEHYDRATION, _4P_METHOXYLISOFLAVONE_DEMETHYLATION,
//		_6P_METHOXYLISOFLAVONE_DEMETHYLATION, ISOFLAVAN_4_OL_DEHYDROXYLATION,
//		DEOXYBENZOIN_DEGRADATION, B_TYPE_PROCYANIDIN_DIMER_DEGRADATION_PATTERN1, B_TYPE_PROCYANIDIN_DIMER_DEGRADATION_PATTERN4,
//		TAURINATED_C24_BILE_ACID_DECONJUGATION_PATTERN1, TAURINATED_C23_BILE_ACID_DECONJUGATION_PATTERN2,
//		GLYCINATED_C24_BILE_ACID_DECONJUGATION_PATTERN1, GLYCINATED_C23_BILE_ACID_DECONJUGATION_PATTERN2,
//		C24_BILE_ACID_7ALPHA_DEHYDROXYLATION_PATTERN1, C23_BILE_ACID_7ALPHA_DEHYDROXYLATION_PATTERN2, _3_HYDROXY_C24_BILE_ACID_DEHYDROGENATION,
//		_7_HYDROXY_C24_BILE_ACID_DEHYDROGENATION, _12_HYDROXY_C24_BILE_ACID_DEHYDROGENATION, C24_BILE_ACID_ETHYLATION,
//		CORTICOSTEROID_21_DEHYDROXYLATION, C24_BILE_ACID_C24_COOH_GLUCURONIDATION,
//
//		DEGRADATION_TO_PHLOROGCLUCINOL_ALDEHYDE,
//		_34_DIHPP_2_OL_DEGRADATION_TO_PHLOROGCLUCINOL_ALDEHYDE, DIHYDROCHALCONE_DEGRADATION_PATTERN1, DIHYDROCHALCONE_DEGRADATION_PATTERN2,
//		DIHYDROCHALCONE_DEGRADATION_PATTERN3, _2P_DIHYDROMETHYLDEOXYBENZOIN_DEHYDROGENATION, HYDROLYSIS_OF_GALLIC_ACID, HYDROLYSIS_OF_PROTOCATECHUIC_ACID,
//		HYDROLYSIS_OF_VANILLIC_ACID, DEMETHYLATION_OF_VANILLIC_ACID, DEGRADATION_OF_ANTHOCYANIDIN_TO_CHALCONE,
//		DEGRADATION_OF_MEDIORESINOL_TO_PINORESINOL, DEGRADATION_OF_PINORESINOL_TO_LARICIRESINOL, DEGRADATION_OF_LARICIRESINOL_TO_SECOISOLARICIRESINOL,
//		DEGRADATION_OF_SECOISOLARICIRESINOL_TO_DIHYDROXYENTERODIOL, DEGRADATION_OF_DIHYDROXYENTERODIOL_TO_ENTERODIOL,
//		DEGRADATION_OF_DIHYDROXYENTERODIOL_TO_DIHYDROXYENTEROLACTONE, DEGRADATION_OF_ENTERODIOL_ENTEROLACTONE,
//		DEGRADATION_OF_DIHYDROXYENTEROLACTONE_TO_ENTEROLACTONE, DEGRADATION_OF_MATAIRESINOL_TO_DIHYDROXYENTEROLACTONE,
//		DEGRADATION_OF_SESAMIN_1, DEGRADATION_OF_SESAMIN_2, DEGRADATION_OF_SESAMIN_3, DEGRADATION_OF_PHENYLVALEROLACTONE,
//		ANTHOCYANIDIN_C_RING_FISSION_PATTERN1, ANTHOCYANIDIN_C_RING_FISSION_PATTERN2,
//		DEHYDROXYLATION_OF_HYDROXY_PHENYL_AND_BENZOIC_ACICDS_PATTERN1, DEHYDROXYLATION_OF_HYDROXY_PHENYL_AND_BENZOIC_ACICDS_PATTERN2,
//		HYDROGENATION_OF_P_HYDROXYCINNAMIC_ACIDS, CHALCONE_DIHYDROGENATION_PATTERN1, CHALCONE_DIHYDROGENATION_PATTERN2,
//		B_TYPE_PROCYANIDIN_DIMER_DEGRADATION_PATTERN2, B_TYPE_PROCYANIDIN_DIMER_DEGRADATION_PATTERN3,
//
//		_3P_O_DEMETHYLATION_OF_FLAVONE, _3_O_DEMETHYLATION_OF_FLAVONE, _5_O_DEMETHYLATION_OF_FLAVONE,
//		_6_O_DEMETHYLATION_OF_FLAVONE, _7_O_DEMETHYLATION_OF_FLAVONE,
//		DIHYDROCHALCONE_HYDROLYSIS, ISOFLAVONE_6_C_DEGLYCOSYLATION, ISOFLAVONE_8_C_DEGLYCOSYLATION,
//		CARDIOLIPIN_DEACYLATION, MONOLYSOCARDIOLIPIN_ACYLATION, STEROID_3_SULFONATION,
//		PHOSPHATIDYLCHOLINE_2_ACYLHYDROLYSIS, PLASMENYLETHANOLAMINE_2_ACYLHYDROLYSIS,
//		PLASMENYLCHOLINE_2_ACYLHYDROLYSIS, PHOSPHATIDATE_2_ACYLHYDROLYSIS, ARYLACETAMDE_DEACETYLATION,
//
//
//		/**
//		 * EC-Based Reactions
//		 */
//		S_3_HYDROXYACYL_COA_DEHYDROGENATION, _3_ALPHA_HYDROXYSTEROID_DEHYDROGENATION, LONG_CHAIN_S_3_HYDROXYACYL_COA_DEHYDROGENATION,
//		_20_BETA_HYDROXYSTEROID_DEHYDROGENATION, _3_BETA_HYDROXY_DELTA_5_STEROID_DEHYDROGENATION,
//		_11_BETA_HYDROXYSTEROID_DEHYDROGENATION, _7_ALPHA_HYDROXYSTEROID_DEHYDROGENATION,
//		_3_BETA_HYDROXYSTEROID_4_ALPHA_CARBOXYLATE_DEHYDROGENATION, ALDEHYDE_REDUCTION, _3_ALPHA_PREGNANE_DEHYDROGENATION,
//		_17_BETA_HYROXYSTEROID_DEHYDROGENATION, VERY_LONG_CHAIN_3R_3_HYDROXYACYL_COA_REDUCTION, _S_2_HYDROXYCARBOXYLATE_DEHYDROGENATION,
//		LONG_CHAIN_ALCOHOL_OXIDATION, BENZALDEHYDE_DEHYDROGENATION, _3_OXO_5_ALPHA_STEROID_DEHYDROGENATION,
//		ACYL_COA_TRANS_2_OXIDOREDUCTION, DELTA_14_STEROL_REDUCTION,
//		// Biol. Chem., Vol. 391, pp. 219–227, February/March 2010 ; DOI 10.1515/BC.2010.015
//		ANTHOCYANIDIN_REDUCTION,
//		VERY_LONG_CHAIN_ENOYL_COA_REDUCTION,
//		SHORT_CHAIN_ACYL_COA_DEHYDROGENATION, MEDIUM_CHAIN_ACYL_COA_DEHYDROGENATION, ACYL_COA_OXIDATION,
//		LONG_CHAIN_ACYL_COA_DEHYDROGENATION, VERY_LONG_CHAIN_ACYL_COA_DEHYDROGENATION, _3_OXOSTEROID_DEHYDROGENATION,
//		STEROL_14_ALPHA_DEMETHYLATION, _3_KETOSTEROID_9ALPHA_HYDROXYLATION,
//		STEROL_17_ALPHA_HYDROXYLATION_PATTERN1,
//		STEROL_17_ALPHA_HYDROXYLATION_PATTERN2,
//		STEROL_11_BETA_HYDROXYLATION, ACYL_COA_11Z_DESATURATION, SPHINGOLIPID_4_DESATURATION, SPHINGOLIPID_8E_DESATURATION,
//		SPHINGOLIPID_10_DESATURATION, DELTA_7_STEROL_56_DESATURATION, DELTA_7_STEROL_56_SATURATION,
//		STEROL_C_17_ACYL_CLEAVAGE_PATTERN1,
//		STEROL_C_17_ACYL_CLEAVAGE_PATTERN2,
//		STEROL_C_17_ACYL_CLEAVAGE_PATTERN3,
//		STEROL_C_17_ACYL_CLEAVAGE_PATTERN4,
//		ANDROGEN_AROMATIZATION,
//
//		SPHINGOLIPID_8Z_DESATURATION,
//		PHOSPHATIDYLETHANOLAMINE_N_METHYLATION, FLAVONE_3P_O_METHYLATION,
//		PHOSPHATIDYL_N_MONOMETHYLETHANOLAMINE_N_METHYLATION, PHOSPHATIDYL_N_DIMETHYLETHANOLAMINE_N_METHYLATION,
//		SPHINGOLIPID_C9_METHYLATION, ACYL_COA_GLYCEROL_3_PHOSPHATE_1_O_ACYL_TRANSFER, ACYL_COA_C_ACYL_TRANSFER, DIACYLGLYCEROL_O_ACYLATION,
//		_2_ACYLGLYCEROL_O_ACYLATION, _1_ACYLGLYCEROPHOSPHOCHOLINE_O_ACYLATION, SPHINGOSINE_N_ACYLATION_REVERSE,
//		PLASMALOGEN_SYNTHESIS_REVERSE, STEROL_O_ACYLATION, PHOSPHATIDYLCHOLINE_STEROL_O_ACYLATION,
//		PHOSPHATIDYLCHOLINE_CHOLESTEROL_O_ACYLATION, PHOSPHATIDYLCHOLINE_CEREBROSTEROL_O_ACYLATION, PHOSPHATIDYLCHOLINE_SITOSTEROL_O_ACYLATION,
//		_1_ACYLGLYCEROL_3_PHOSPHATE_O_ACYLATION, _1_ACYLGLYCEROL_3_PHOSPHATE_O_ACYLATION_REVERSE,
//		_1_ALKYLGLYCEROPHOSPHOCHOLINE_O_ACETYLATION, LONG_CHAIN_ALCOHOL_O_ACYLATION, RETINOL_O_FATTY_ACYLATION,
//		L_CYSTEINE_S_CONJUGATE_N_ACETYLATION, ARALKYLAMINE_N_ACETYLATION, ARALKYLAMINE_N_ACETYLATION_PATTERN2,
//		PEPTIDE_ALPHA_N_ACETYLATION,
//		N_HYDROXYARYLAMINE_O_ACETYLATION, N_HYDROXYL_N_ARYLACETAMIDE_O_ACETYLATION,
//		_1_ALKENYLGLYCEROPHOSPHOETHANOLAMINE_O_ACETYLATION_REVERSE,
//		ALCOHOL_O_CINNAMOYL_TRANSFER_REVERSE, ANTHOCYANIN_5_6PPP_HYDROXYCINNAMOYL_TRANSFER_REVERSE,
//		ANTHOCYANIN_6PP_MALONYL_TRANSFER_REVERSE, VERY_LONG_CHAIN_3_OXOACYL_COA_SYNTHESIS,
//		VERY_LONG_CHAIN_3_OXOACYL_COA_SYNTHESIS_REVERSE, ANTHOCYANIDIN_3O_GLUCOSIDE_6PP_DEACYLATION,
//		_2_HYDROXYACYLSPHINGOSINE_1_BETA_GALACTOSYL_TRANSFER, _2_HYDROXYACYLSPHINGOSINE_1_BETA_GALACTOSYL_TRANSFER_REVERSE,
//		GM2_GANGLIOSIDE_GALACTOSYL_TRANSFER, CERAMIDE_GLUCOSYLATION_PATTERN1, CERAMIDE_GLUCOSYLATION_PATTERN2, CERAMIDE_GLUCOSYLATION_PATTERN3,
//		FLAVONOL_3_O_GLUCOSYLATION, FLAVONOL_3_O_DEGLUCOSYLATION,
//		GANGLIOSIDE_GM3_ACETYLGALACTOSAMINE_TRANSFER, GANGLIOSIDE_GD3_ACETYLGALACTOSAMINE_TRANSFER,
//		BETA_D_GALACTOSYL_BETA_D_GLUCOSYL_CERAMIDE_ACETYLGALACTOSAMINE_TRANSFER, ANTHOCYANIDIN_3O_GLUCOSYLATION1,
//		ANTHOCYANIDIN_3O_GLUCOSYLATION2, ANTHOCYANIDIN_3O_DEGLUCOSYLATION, _1_2_DIACYLGLYCEROL_3_GLUCOSYLATION,
//		FLAVONOL_3O_GLUCOSIDE_L_RHAMNOSYLATION, FLAVONOL_3O_GLUCOSIDE_L_DERHAMNOSYLATION, STEROL_3BETA_DEGLUCOSYLATION,
//		PHOSPHATIDYLINOSITOL_N_ACETYLGLUCOSAMINYLATION, FLAVONOL_3O_GLUCOSIDE_GLUCOSYLATION,
//		FLAVONOL_3O_GLUCOSYL_12_GLUCOSIDE_DEGLUCOSYLATION, DIGALACTOSYLDIACYLGLYCEROL_SYNTHESIS,
//		GLUCOSYLCERAMIDE_BETA_1_4_GALACTOSYL_TRANSFER, LACTOSYLCERAMIDE_N_ACETYLNEURAMINATE_TRANSFER,
//		ALKYLGLYCERONE_PHOSPHATE_SYNTHESIS, AROMATIC_AMINO_ACID_TRANSAMINATION, N_ACYL_MANNOSAMINE_1_PHOSPHORYLATION,
//		N_ACYL_MANNOSAMINE_2_PHOSPHORYLATION, _1_PHOSPHATIDYLINOSITOL_4_PHOSPHORYLATION,
//		_1_PHOSPHATIDYL_1D_MYO_INOSITOL_4_PHOSPHATE_5_PHOSPHORYLATION, _1_MONOACYLGLYCEROL_PHOSPHORYLATION,
//		_2_MONOACYLGLYCEROL_PHOSPHORYLATION, _1_PHOSPHATIDYL_1D_MYO_INOSITOL_3_PHOSPHORYLATION, CERAMIDE_PHOSPHORYLATION,
//		_1_PHOSPHATIDYL_1D_MYO_INOSITOL_5_PHOSPHATE_4_PHOSPHORYLATION, _1_PHOSPHATIDYL_1D_MYO_INOSITOL_3_PHOSPHATE_5_PHOSPHORYLATION,
//		_1_PHOSPHATIDYL_1D_MYO_INOSITOL_4_5_BISPHOSPHATE_3_PHOSPHORYLATION, _1_PHOSPHATIDYL_1D_MYO_INOSITOL_4_PHOSPHATE_3_PHOSPHORYLATION,
//		CYTIDINE_TRANSFER_TO_N_ACYLNEURAMINATE, PHOSPHOCHOLINE_TRANSFER_TO_12_DIACYLGLYCEROL, SERINE_TRANSFER_TO_CDP_DIACYLGLYCEROL,
//		INOSITOL_3_PHOSPHATE_TRANSFER_TO_CDP_DIACYLGLYCEROL, N_ACYLSPHINGOID_PHOSPHOCHOLINE_TRANSFER,
//		PHOSPHATIDYLSERINE_SYNTHESIS_FROM_PHOSPHATIDYLETHANOLAMINE,
//		PHOSPHATIDYLSERINE_SYNTHESIS_FROM_PHOSPHATIDYLCHOLINE,
//		_1_ALKYL_2_ACYL_GLYCEROPHOSPHOETHANOLAMINE_FROM_1_ALKYL_2_ACYLGLYCEROL,
//		_1_ALKENYL_2_ACYL_GLYCEROPHOSPHOETHANOLAMINE_FROM_1_ALKYL_2_ACYLGLYCEROL,
//		CARDIOLIPIN_SYNTHESIS, SULFATION_OF_PRIMARY_ALCOHOL,
//		SULFATION_OF_SECONDARY_ALCOHOL, GALACTOSYLCERAMIDE_3P_SULFATION, DIGALACTOSYLCERAMIDE_3P_SULFATION,
//		GALACTOSYL_1_ALKYL_2_ACYL_SULFATION,
//		HYDROLYSIS_OF_CARBOXYLIC_ACID_ESTER_PATTERN1,
//		HYDROLYSIS_OF_CARBOXYLIC_ACID_ESTER_PATTERN2,
//		PHENYLACETATE_ESTER_HYDROLYSIS, TRIACYLGLYCEROL_ACYLHYDROLYSIS,
//		PHOSPHATIDYLETHANOLAMINE_2_ACYLHYDROLYSIS, _2_LYSOPHOSPHATIDYLETHANOLAMINE_ACYLHYDROLYSIS, ACYLCHOLINE_ACYLHYDROLYSIS,
//		STERYL_ESTER_ACYLHYDROLYSIS, _1_MONOACYLGLYCEROL_HYDROLYSIS, _2_MONOACYLGLYCEROL_HYDROLYSIS,
//		PHOSPHATIDYLCHOLINE_1_ACYLHYDROLYSIS, _1_ALKYL_2_ACETYL_GLYCEROPHOSPHOCHOLINE_ACETOHYDROLYSIS,
//		LONG_CHAIN_ACYL_COA_HYDROLYSIS, S_2_HYDROXYACYL_GLUTATHIONE_HYDROLYSIS, PHOSPHATE_MONOESTER_DEPHOSPHORYLATION,
//		_12_DIACYLGLYCEROL_3_PHOSPHATE_DEPHOSPHORYLATION, _1_ALKYL_2_ACYLGLYCEROL_3_PHOSPHATE_DEPHOSPHORYLATION,
//		_5P_RIBONUCLEOTIDE_DEPHOSPHORYLATION, _3P_RIBONUCLEOTIDE_DEPHOSPHORYLATION, PHOSPHATIDYLGLYCEROPHOSPHATE_DEPHOSPHORYLATION,
//		N_ACYLNEURAMINATE_9_PHOSPHATE_DEPHOSPHORYLATION, PHOSPHATIDYLINOSITOL_45_BISPHOSPHATE_DEPHOSPHORYLATION_5,
//		PHOSPHATIDYLINOSITOL_3_PHOSPHATE_DEPHOSPHORYLATION, PHOSPHATIDYLINOSITOL_34_BISPHOSPHATE_DEPHOSPHORYLATION_4,
//		PHOSPHATIDYLINOSITOL_345_TRISPHOSPHATE_DEPHOSPHORYLATION_3, PHOSPHATIDYLINOSITOL_45_BISPHOSPHATE_DEPHOSPHORYLATION_4,
//		_12_DIACYLGLYCEROL_3_DIPHOSPHATE_DEPHOSPHORYLATION, PHOSPHATIDYLINOSITOL_345_TRISPHOSPHATE_DEPHOSPHORYLATION_5,
//		PHOSPHATIDYLINOSITOL_35_BISPHOSPHATE_DEPHOSPHORYLATION_3, PHOSPHATIDYLCHOLINE_PHOSPHATIDOHYDROLYSIS,
//		PHOSPHATIDYLINOSITOL_45_BISPHOSPHATE_CLEAVAGE, SPHINGOMYELIN_PHOSPHOCHLINE_CLEAVAGE,
//		_2P_3P_CYCLIC_NUCLEOTIDE_HYDROLYSIS_TO_3P_NUCLEOTIDE, _3P_5P_CYCLIC_NUCLEOTIDE_HYDROLYSIS_TO_3P_NUCLEOTIDE,
//		_1_ALKYLGLYCEROL_3_PHOSPHOETHANOLAMINE_HYDROLYSIS_TO_1_ALKYLGLYCEROL_3_PHOSPHATE,
//		GLYCOSYLPHOSPHATIDYLINOSITOL_HYDROLYSIS_TO_PHOSPHATIDATE, N_ACYLPHOSPHATIDYLETHANOLAMINE_PHOSPHATIDOHYDROLYSIS,
//		ARYLSULFATE_SULFOHYDROLYSIS, CEREBROSIDE_3_SULFATE_SULFOHYDROLYSIS, ARYLDIALKYLPHOSPHATE_PHOSPHOHYDROLYSIS,
//		DIGALACTOSYLDIACYLGLYCEROL_GALACTO_HYDROLYSIS, TRIHEXOSYLCERAMIDE_GALACTO_HYDROLYSIS, DIGALACTOSYLCERAMIDE_GALACTO_HYDROLYSIS_PATTERN1,
//		DIGALACTOSYLCERAMIDE_GALACTO_HYDROLYSIS_PATTERN2, BETA_D_GALACTOSIDE_GALACTO_HYDROLYSIS_PATTERN1,
//		BETA_D_GALACTOSIDE_GALACTO_HYDROLYSIS_PATTERN2, BETA_D_GALACTOSIDE_GALACTO_HYDROLYSIS_PATTERN3, GLUCOSYLCERAMIDE_GLUCO_HYDROLYSIS,
//		GALACTOSYLCERAMIDE_GALACTO_HYDROLISIS, GLYCOSYLCERAMIDE_GLYCOSYL_HYDROLYSIS, THIOGLUCOSINOLATE_HYDROLYSIS, RIBOSYLPYRIMIDINE_RIBOHYDROLYSIS,
//		ALKENYLGLYCERO_3_PHOSPHOCHOLINE_HYDROLYSIS_TO_GLYCERO_3_PHOSPHOCHOLINE, ALKENYLGLYCERO_3_PHOSPHOETHANOLAMINE_HYDROLYSIS_TO_GLYCERO_3_PHOSPHOETHANOLAMINE,
//		_2P_3P_CYCLIC_NUCLEOTIDE_HYDROLYSIS_TO_2P_NUCLEOTIDE, GLYCEROPHOSPHODIESTER_HYDROLYSIS,
//		N_ACYL_ALIPHATIC_L_AMINO_ACID_AMIDOHYDROLYSIS, N_ACETYL_L_CYSTEINE_S_CONJUGATE_AMIDOHYDROLYSIS,
//		N_ACYL_L_ASPARTATE_AMIDOHYDROLYSIS, N_ACYLSPHINGOSINE_AMIDOHYDROLYSIS, N_ACYL_AROMATIC_L_AMINO_ACID_AMIDOHYDROLYSIS,
//		NUCLEOSIDE_DIPHOSPHATE_PHOSPHOHYDROLYSIS, ACYLPHOSPHATE_PHOSPHOHYDROLYSIS, DINUCLEOTIDE_HYDROLYSIS, NUCLEOSIDE_TRIPHOSPHATE_PHOSPHOHYDROLYSIS,
//		NUCLEOSIDE_TRIPHOSPHATE_DIPHOSPHATE_CLEAVAGE, _3_ACYLPYRUVATE_ACYLHYDROLYSIS, PHOSPHATIDYLSERINE_DECARBOXYLATION, _3S_3_HYDROXYACYL_COA_DEHYDRATION,
//		VERY_LONG_CHAIN_3R_3_HYDROXYACYL_COA_DEHYDRATION, PEPTIDOAMIDOGLYCOLATE_PEPTIDYLAMIDE_LIGATION, STEROID_DELTA_ISOMERIZATION,
//		LONG_CHAIN_FATTY_ACYL_COA_LIGATION, KETO_HYDROLYSIS_PATTERN2, KETO_HYDROLYSIS_PATTERN3, KETO_HYDROLYSIS_PATTERN4,
//		EPOXIDE_HYDROLYSIS,
//		KETO_ENOL_TAUTOMERIZATION_PATTERN2, KETO_ENOL_TAUTOMERIZATION_PATTERN3, KETO_ENOL_TAUTOMERIZATION_PATTERN4,
//		KETO_ENOL_TAUTOMERIZATION_PATTERN5, KETO_ENOL_TAUTOMERIZATION_PATTERN6,
//
//		 LONG_CHAIN_ACYL_COA_REDUCTION, STEROL_O_ACYLATION_REVERSE, _1_ALKYL_2_ACYL_3_GLYCEROPHOSPHOCHOLINE_DEACYLATION,
//			_1_ACYL_2_ALKYL_3_GLYCEROPHOSPHOCHOLINE_DEACYLATION, _12_DIACYLGLYCEROL_3_PHOSPHATE_1_DEACYLATION, ALDEHYDE_DEHYDROGENATION,
//			ARYL_ALDEHYDE_DEHYDROGENATION, LONG_CHAIN_ALDEHYDE_DEHYDROGENATION, FLAVONOL_3O_BETA_GLUCOSIDE_O_MANNOSYL_TRANSFER,
//			FLAVONOL_3O_BETA_GLUCOSIDE_O_MANNOSYL_TRANSFER_REVERSE, _3_OXO_5_BETA_STEROID_DEHYDROGENATION,
//			FLAVONOL_3O_GLUCOSYL_12_GLUCOSYL_12_GLUCOSYL_DEGLUCOSYLATION, _12_DIACYLGLYCEROL_PHOSPHORYLATION,
//			SULFATION_OF_PHENOLIC_STEROID, N_HYDROXYARYLAMINE_SULFATION, _5P_ACYLPHOSPHOADENOSINE_ACYLHYDROLYSIS,
//			N_ALKYLGLYCINE_OXIDATION, PEPTIDYLAMIDOGLYCOLATE_PEPTIDYLAMIDE_LIGATION, N_ACETYL_L_ASPARTATE_S_CONJUGATE_AMIDOHYDROLYSIS,
//			D_2_HYDROXY_ACID_DEHYDROGENATION, L_2_HYDROXYCARBOXYLATE_DEHYDROGENATION, _1_O_ALKYL_2_ACETYL_SN_GLYCEROL_DEACETYLATION,
//			NADPH_ASSISTED_DEHYDROGENATION_PATTERN1,
//			NADPH_ASSISTED_DEHYDROGENATION_PATTERN2, NADPH_ASSISTED_DEHYDROGENATION_PATTERN3,
//			NADPH_ASSISTED_DEHYDROGENATION_PATTERN4, NADPH_ASSISTED_DEHYDROGENATION_PATTERN5, NADPH_ASSISTED_DEHYDROGENATION_PATTERN6,
//			NADPH_ASSISTED_DEHYDROGENATION_PATTERN7, NADPH_ASSISTED_DEHYDROGENATION_PATTERN8, NADPH_ASSISTED_DEHYDROGENATION_PATTERN9,
//			NADPH_ASSISTED_DEHYDROGENATION_PATTERN10,
//			REDUCTION_OF_NITROBENZE_TO_AMINOBENZENE,
//			OXIDATION_OF_N_SUBSTITUTED_PYRROLIDINE_IMINIUM,
//			OXIDATION_OF_N_SUBSTITUTED_PIPERIDINE_IMINIUM,
//			OXIDATION_OF_PYRIMIDINE_PATTERN1,
//			OXIDATION_OF_PYRIMIDINE_PATTERN2,
//			OXIDATION_OF_PYRIMIDINE_PHTHALAZINE,
//			OXIDATION_OF_PYRIMIDINE_PATTERN3,
//			ETHANOLAMINEPHOSPHATE_TRANSFER_TO_12_DIACYLGLYCEROL,SPHINGANINE_C4_HYDROXYLATION, GLYCERONE_PHOSPHATE_O_ACYLATION,
//			SN_GLYCEROL_3_PHOSPHATE_TRANSFER_TO_CDP_DIACYLGLYCEROL, N_ACYL_L_HOMOSERINE_LACTONE_LACTONOHYDROLYSIS,
//			_12_DIACYLGLYCEROL_3_PHOSPHATE_CITIDYL_TRANSFER, _12_DIACYL_3_BETA_GLALACTOSYL_SN_GLYCEROLALACTOSYL_ACYL_HYDROLYSIS,
//			_1_2_DIACYLGLYCEROL_SN1_SPECIFIC_ACYLHYDROLYSIS, HYDROLYSIS_OF_TERMINAL_14_LINKED_ALPHA_D_GLUCOSE_PATTERN1,
//			HYDROLYSIS_OF_TERMINAL_BETA_D_GLUCOSE_PATTERN1, ALPHA_BETA_MANNOSIDE_MANNOHYDROLYSIS,
//			D_GLYCOSIDE_HYDROLYSIS, BETA_D_GLUCORONOSIDE_GLUCURONOSOHYDROLYSIS,
//			BETA_GLUCORONOSIDE_GLUCURONOSOHYDROLYSIS, ALPHA_N_ACETYL_GLUCOSAMINIDE_N_ACETYL_GLUCOSAMINOHYDROLYSIS,
//			ALL_TRANS_RETINYL_ESTER_ACYLHYDROLYSIS, ALPHA_L_RHAMNOSIDE_RHAMNOHYDROLYSIS, HYDROLYSIS_OF_TERMINAL_ALPHA_GALACTOSE,
//			HYDROLYSIS_OF_TERMINAL_BETA_GALACTOSE, _4P_DEHYDROXYLATION_OF_SUBSTITUTED_BENZENE, BETA_D_GALACTOSIDE_6_ACETYLATION,
//			QUINONE_REDUCTION_PATTERN1, QUINONE_REDUCTION_PATTERN2,
//			_3P_DEHYDROXYLATION_OF_SUBSTITUTED_BENZENE,
//
//
//			// Stability and biotransformation of various dietary anthocyanins in vitro; Eur J Nutr (2006) 45 : 7–18
//			// DOI 10.1007/s00394-005-0557-8
//			FLAVYLIUM_HYDRATION,
//
//			THIOGLUCOSIDE_HYDROLYSIS, GLYCOSIDE_HYDROLYSIS,
//			THIOHYDROXIMATE_O_SULFOHYDROLYSIS, N_ACETYLGLUCOSAMINYL_PHOSPHATIDYLINOSITOL_N_DEACETYLATION,
//			ALKYLGLYCEROL_3_PHOSPHATE_OXIDATION, ACYLGLYCEROL_3_PHOSPHATE_OXIDATION,
//			ACYLGLYCERONE_3_PHOSPHATE_REDUCTION, LACTOSYLCERAMIDE_4_ALPHA_GALACTOSE_TRANSFER,
//			HYDROLYSIS_OF_CYCLIC_N_ACYLUREA, HYDROLYSIS_OF_CYCLIC_SECONDARY_CARBOXAMIDE_PATTERN_1,
//			HYDROLYSIS_OF_CYCLIC_SECONDARY_CARBOXAMIDE_PATTERN_2, HYDROLYSIS_OF_CYCLIC_TERTIARY_CARBOXAMIDE_PATTERN_1,
//			HYDROLYSIS_OF_CYCLIC_N_ACYLGUANIDINE,
//			TRANS_23_DIDEHYDROACYL_COA_REDUCTION,
//			STEROL_21_HYDROXYLATION,
//			STEROL_2_HYDROXYLATION_PATTERN1,
//			STEROL_2_HYDROXYLATION_PATTERN2,
//			STEROL_4_HYDROXYLATION_PATTERN1,
//			STEROL_4_HYDROXYLATION_PATTERN2,
//			STEROL_6_HYDROXYLATION_PATTERN1,
//			STEROL_6_HYDROXYLATION_PATTERN2,
//			STEROL_7_HYDROXYLATION_PATTERN1,
//			STEROL_7_HYDROXYLATION_PATTERN2,
//			STEROL_7_HYDROXYLATION_PATTERN3,
//			STEROL_16_HYDROXYLATION_PATTERN1,
//			STEROL_16_HYDROXYLATION_PATTERN2,
//			STEROL_3_OH_SULFATION,
//			STEROL_7_OH_SULFATION,
//			STEROL_7_OH_SULFATION_PATTERN2,
//			STEROL_12_OH_SULFATION,
//			STEROL_12_OH_SULFATION_PATTERN2,
//			_7_OH_HYDROXYLATION_OF_FLAVONOL,
//			_3_R_OXOACYL_REDUCTION,
//			_2_TRANS_ENOYL_FORMATION_FROM_3_R_OXOACYL,
//			_7_OH_GLUCURONIDATION_OF_STEROL,
//			_3_OH_GLUCURONIDATION_OF_STEROL_PATTERN2,
//			_6_OH_GLUCURONIDATION_OF_STEROL_PATTERN2,
//			_7_OH_GLUCURONIDATION_OF_STEROL_PATTERN2,
//			_17_OH_GLUCURONIDATION_OF_STEROL_PATTERN2,
//			NITROREDUCTION_OF_NITROARENE_TO_HYDROXYLAMINE_PATTERN1,
//			NITROREDUCTION_OF_NITROARENE_TO_NITROSOARENE_PATTERN1,
//			NITROREDUCTION_OF_NITROARENE_TO_NITROSOARENE_PATTERN2,
//			NITROREDUCTION_OF_NITROARENE_TO_NITROSOARENE_PATTERN3,
//			NITROREDUCTION_OF_NITROARENE_TO_NITROSOARENE_PATTERN4,
//			NITROREDUCTION_OF_NITROSOARENE_TO_ARYLHYDROXYLAMINE_PATTERN1,
//			NITROREDUCTION_OF_NITROSOARENE_TO_ARYLHYDROXYLAMINE_PATTERN2,
//			NITROREDUCTION_OF_NITROSOARENE_TO_ARYLHYDROXYLAMINE_PATTERN3,
//			NITROREDUCTION_OF_NITROSOARENE_TO_ARYLHYDROXYLAMINE_PATTERN4,
//			REDUCTION_OF_ARYLHYDROXYLAMINE_TO_ARYLAMINE_PATTERN1,
//			REDUCTION_OF_ARYLHYDROXYLAMINE_TO_ARYLAMINE_PATTERN2,
//			REDUCTION_OF_ARYLHYDROXYLAMINE_TO_ARYLAMINE_PATTERN3,
//			REDUCTION_OF_ARYLHYDROXYLAMINE_TO_ARYLAMINE_PATTERN4,
//			NITROREDUCTION_OF_POLYCYCLIC_NITROARENE_PATTERN1,
//			NITROREDUCTION_OF_POLYCYCLIC_NITROARENE_PATTERN2,
//			HYDROLYSIS_OF_ACYLCARNITINE,
//			HYDROLISIS_OF_ARYL_ACYLAMIDE,
//			REDUCTIVE_LACTONIZATION_OF_QUINONE_PROPIONIC_ACID_PATTERN1,
//			REDUCTIVE_LACTONIZATION_OF_QUINONE_PROPIONIC_ACID_PATTERN2,
//			SULFITE_REDUCTION,
//			REDUCTION_OF_AZOBENZENE,
//			NITRILE_DEGRADATION_TO_AMIDE_PATTERN1,
//			NITRILE_DEGRADATION_TO_AMIDE_PATTERN2,
//			NITRILE_DEGRADATION_TO_AMIDE_PATTERN3,
//			NITRILE_DEGRADATION_TO_CARBOXYLIC_ACID,
//			ALIPHATIC_NITRILE_DEGRADATION_TO_CARBOXYLIC_ACID,
//			HYDROLYSIS_OF_FERULIC_ACID_ESTER,
//			ACYL_HYDROLYSIS_OF_4_NITROPHENYL_ESTER,
//			_2_HALOACID_DEHALOGENATION,
//			_2_HALOALKANE_DEHALOGENATION,
//			HYROLYSIS_OF_HYDANTOIN_PATTERN1,
//			HYROLYSIS_OF_HYDANTOIN_PATTERN2,
//			HYROLYSIS_OF_HYDROPYRIMIDINE_PATTERN1,
//			HYROLYSIS_OF_HYDROPYRIMIDINE_PATTERN2,
//			HYROLYSIS_OF_HYDROPYRIMIDINE_PATTERN3,
//			DIENELACTONE_HYDROLYSIS,
//			C24_BILE_ACID_COA_ESTERIFICATION_PATTERN1,
//			C23_BILE_ACID_COA_ESTERIFICATION_PATTERN2,
//			C24_BILE_ACID_COA_TAURINATION_PATTERN1,
//			C23_BILE_ACID_COA_TAURINATION_PATTERN2,
//			_3_7_12_OH_CHOLESTANE_OXIDATION,
//			_3_OXO_7_12_OH_CHOLESTANE_OXIDATION,
//			_3_7_12_OH_CHOLESTANE_27_HYDROXYLATION,
//			HYDROLYSIS_OF_SECONDARY_ALKYL_SULFATE_ESTER_PATTERN1,
//
//		/**
//		 * 	Environmental microbial metabolic reactions.
//		 *  These were from the UM-PPS.
//		 */
//		EAWAG_RULE_BT0001, EAWAG_RULE_BT0008, EAWAG_RULE_BT0002, EAWAG_RULE_BT0003, EAWAG_RULE_BT0005_PATTERN1,
//		EAWAG_RULE_BT0005_PATTERN2, EAWAG_RULE_BT0005_PATTERN3, EAWAG_RULE_BT0011,
//		EAWAG_RULE_BT0012, EAWAG_RULE_BT0013, EAWAG_RULE_BT0014, EAWAG_RULE_BT0020, EAWAG_RULE_BT0021_PATTERN1,
//		EAWAG_RULE_BT0021_PATTERN2, EAWAG_RULE_BT0022_PATTERN1, EAWAG_RULE_BT0022_PATTERN2, EAWAG_RULE_BT0023_PATTERN1, EAWAG_RULE_BT0023_PATTERN2,
//		EAWAG_RULE_BT0024_PATTERN1, EAWAG_RULE_BT0024_PATTERN2, EAWAG_RULE_BT0026, EAWAG_RULE_BT0027,
//		EAWAG_RULE_BT0028, EAWAG_RULE_BT0029, EAWAG_RULE_BT0030, EAWAG_RULE_BT0031, EAWAG_RULE_BT0033,
//		EAWAG_RULE_BT0034_PATTERN1, EAWAG_RULE_BT0034_PATTERN2, EAWAG_RULE_BT0035, EAWAG_RULE_BT0036,
//		EAWAG_RULE_BT0037_PATTERN1, EAWAG_RULE_BT0037_PATTERN2, EAWAG_RULE_BT0040, EAWAG_RULE_BT0041,
//		EAWAG_RULE_BT0042, EAWAG_RULE_BT0044, EAWAG_RULE_BT0049, EAWAG_RULE_BT0050, EAWAG_RULE_BT0051_PATTERN1,
//		EAWAG_RULE_BT0051_PATTERN2, EAWAG_RULE_BT0051_PATTERN3, EAWAG_RULE_BT0051_PATTERN4,
//		EAWAG_RULE_BT0055_PATTERN1, EAWAG_RULE_BT0055_PATTERN2, EAWAG_RULE_BT0056, EAWAG_RULE_BT0058,
//		EAWAG_RULE_BT0060, EAWAG_RULE_BT0061, EAWAG_RULE_BT0062, EAWAG_RULE_BT0063_PATTERN1,
//		EAWAG_RULE_BT0063_PATTERN2, EAWAG_RULE_BT0064, EAWAG_RULE_BT0065_PATTERN1, EAWAG_RULE_BT0065_PATTERN2, EAWAG_RULE_BT0066_PATTERN1,
//		EAWAG_RULE_BT0066_PATTERN2, EAWAG_RULE_BT0067_PATTERN1, EAWAG_RULE_BT0067_PATTERN2, EAWAG_RULE_BT0068, EAWAG_RULE_BT0069, EAWAG_RULE_BT0070,
//		EAWAG_RULE_BT0071, EAWAG_RULE_BT0072, EAWAG_RULE_BT0073, EAWAG_RULE_BT0077, EAWAG_RULE_BT0078, EAWAG_RULE_BT0079,
//		EAWAG_RULE_BT0080, EAWAG_RULE_BT0082, EAWAG_RULE_BT0086_PATTERN1, EAWAG_RULE_BT0086_PATTERN2, EAWAG_RULE_BT0102,
//		EAWAG_RULE_BT0103_PATTERN1, EAWAG_RULE_BT0103_PATTERN2, EAWAG_RULE_BT0104_PATTERN1, EAWAG_RULE_BT0104_PATTERN2,
//		EAWAG_RULE_BT0105, EAWAG_RULE_BT0107, EAWAG_RULE_BT0108, EAWAG_RULE_BT0110, EAWAG_RULE_BT0124, EAWAG_RULE_BT0128, EAWAG_RULE_BT0143, EAWAG_RULE_BT0144,
//		EAWAG_RULE_BT0146_PATTERN1_A, EAWAG_RULE_BT0146_PATTERN1_B, EAWAG_RULE_BT0146_PATTERN1_C, EAWAG_RULE_BT0146_PATTERN2,
//		EAWAG_RULE_BT0147, EAWAG_RULE_BT0149_PATTERN1, EAWAG_RULE_BT0153_PATTERN1, EAWAG_RULE_BT0153_PATTERN2, EAWAG_RULE_BT0154,
//		EAWAG_RULE_BT0156_PATTERN1, EAWAG_RULE_BT0156_PATTERN2, EAWAG_RULE_BT0156_PATTERN3,
//		EAWAG_RULE_BT0158_PATTERN1, EAWAG_RULE_BT0158_PATTERN2, EAWAG_RULE_BT0162, EAWAG_RULE_BT0166_PATTERN1,
//		EAWAG_RULE_BT0166_PATTERN2, EAWAG_RULE_BT0173, EAWAG_RULE_BT0174, EAWAG_RULE_BT0177,
//		EAWAG_RULE_BT0180, EAWAG_RULE_BT0184_PATTERN1,
//		EAWAG_RULE_BT0184_PATTERN2, EAWAG_RULE_BT0188, EAWAG_RULE_BT0189, EAWAG_RULE_BT0190, EAWAG_RULE_BT0192,
//		EAWAG_RULE_BT0193, EAWAG_RULE_BT0198, EAWAG_RULE_BT0199, EAWAG_RULE_BT0200_PATTERN1, EAWAG_RULE_BT0200_PATTERN2,
//		EAWAG_RULE_BT0202, EAWAG_RULE_BT0206, EAWAG_RULE_BT0208, EAWAG_RULE_BT0214, EAWAG_RULE_BT0218, EAWAG_RULE_BT0225,
//		EAWAG_RULE_BT0226, EAWAG_RULE_BT0227, EAWAG_RULE_BT0234, EAWAG_RULE_BT0242_PATTERN1, EAWAG_RULE_BT0242_PATTERN2,
//		EAWAG_RULE_BT0242_PATTERN3, EAWAG_RULE_BT0243, EAWAG_RULE_BT0255_PATTERN1, EAWAG_RULE_BT0255_PATTERN2, EAWAG_RULE_BT0257, EAWAG_RULE_BT0259, EAWAG_RULE_BT0260,
//		EAWAG_RULE_BT0275, EAWAG_RULE_BT0281, EAWAG_RULE_BT0284, EAWAG_RULE_BT0286, EAWAG_RULE_BT0291_PATTERN1, EAWAG_RULE_BT0291_PATTERN2,
//		EAWAG_RULE_BT0295_PATTERN1, EAWAG_RULE_BT0295_PATTERN2, EAWAG_RULE_BT0297, EAWAG_RULE_BT0298, EAWAG_RULE_BT0304,
//		EAWAG_RULE_BT0305, EAWAG_RULE_BT0306, EAWAG_RULE_BT0311, EAWAG_RULE_BT0313, EAWAG_RULE_BT0316, EAWAG_RULE_BT0318_PATTERN1,
//		EAWAG_RULE_BT0318_PATTERN2, EAWAG_RULE_BT0320, EAWAG_RULE_BT0323, EAWAG_RULE_BT0325, EAWAG_RULE_BT0334, EAWAG_RULE_BT0343, EAWAG_RULE_BT0344, EAWAG_RULE_BT0347,
//		EAWAG_RULE_BT0348_PATTERN1, EAWAG_RULE_BT0348_PATTERN2,
//		EAWAG_RULE_BT0349_PATTERN1, EAWAG_RULE_BT0349_PATTERN2, EAWAG_RULE_BT0349_PATTERN3,
//		EAWAG_RULE_BT0349_PATTERN4, EAWAG_RULE_BT0351_PATTERN1, EAWAG_RULE_BT0351_PATTERN2,
//		EAWAG_RULE_BT0351_PATTERN3, EAWAG_RULE_BT0351_PATTERN4, EAWAG_RULE_BT0351_PATTERN5,
//		EAWAG_RULE_BT0351_PATTERN6, EAWAG_RULE_BT0351_PATTERN7, EAWAG_RULE_BT0351_PATTERN8,
//		EAWAG_RULE_BT0356_PATTERN1, EAWAG_RULE_BT0356_PATTERN2, EAWAG_RULE_BT0356_PATTERN3, EAWAG_RULE_BT0353,
//		EAWAG_RULE_BT0357_PATTERN1, EAWAG_RULE_BT0357_PATTERN2, EAWAG_RULE_BT0359, EAWAG_RULE_BT0361, EAWAG_RULE_BT0362_PATTERN1,
//		EAWAG_RULE_BT0362_PATTERN2, EAWAG_RULE_BT0362_PATTERN4, EAWAG_RULE_BT0363, EAWAG_RULE_BT0365,
//		EAWAG_RULE_BT0366_PATTERN1, EAWAG_RULE_BT0366_PATTERN2, EAWAG_RULE_BT0368,
//		EAWAG_RULE_BT0369, EAWAG_RULE_BT0370, EAWAG_RULE_BT0372, EAWAG_RULE_BT0374_PATTERN1,
//		EAWAG_RULE_BT0374_PATTERN2, EAWAG_RULE_BT0376, EAWAG_RULE_BT0377, EAWAG_RULE_BT0379, EAWAG_RULE_BT0385,
//		EAWAG_RULE_BT0386, EAWAG_RULE_BT0388_PATTERN1, EAWAG_RULE_BT0388_PATTERN2, EAWAG_RULE_BT0388_PATTERN3, EAWAG_RULE_BT0388_PATTERN4,
//		EAWAG_RULE_BT0391_PATTERN1, EAWAG_RULE_BT0391_PATTERN2, EAWAG_RULE_BT0401, EAWAG_RULE_BT0397_PATTERN1,
//		EAWAG_RULE_BT0397_PATTERN2, EAWAG_RULE_BT0405, EAWAG_RULE_BT0408, EAWAG_RULE_BT0409,
//		EAWAG_RULE_BT0416_PATTERN1, EAWAG_RULE_BT0416_PATTERN2, EAWAG_RULE_BT0418_PATTERN1, EAWAG_RULE_BT0418_PATTERN2, EAWAG_RULE_BT0421, EAWAG_RULE_BT0423_PATTERN1,
//		EAWAG_RULE_BT0423_PATTERN2, EAWAG_RULE_BT0428, EAWAG_RULE_BT0430, EAWAG_RULE_BT0432_PATTERN1,
//		EAWAG_RULE_BT0432_PATTERN2, EAWAG_RULE_BT0437_PATTERN1,
//		EAWAG_RULE_BT0437_PATTERN2, EAWAG_RULE_BT0441, EAWAG_RULE_BT0442, EAWAG_RULE_BT0443,
//		EAWAG_RULE_BT0195, EAWAG_RULE_BT0209, EAWAG_RULE_BT0219, EAWAG_RULE_BT0237,
//		EAWAG_RULE_BT0340_PATTERN1, EAWAG_RULE_BT0340_PATTERN2, EAWAG_RULE_BT0340_PATTERN3, EAWAG_RULE_BT0427,
//		EAWAG_RULE_BT0045, EAWAG_RULE_BT0231,
//		EAWAG_RULE_BT0241, EAWAG_RULE_BT0254_PATTERN1, EAWAG_RULE_BT0254_PATTERN2, EAWAG_RULE_BT0332, EAWAG_RULE_BT0333,
//		EAWAG_RULE_BT0375, EAWAG_RULE_BT0389, EAWAG_RULE_BT0350_PATTERN1, EAWAG_RULE_BT0350_PATTERN2, EAWAG_RULE_BT0402,
//		EAWAG_RULE_BT0373, EAWAG_RULE_BT0383,
//		EAWAG_RULE_BT0210, EAWAG_RULE_BT0337_PATTERN1, EAWAG_RULE_BT0337_PATTERN2,
//		EAWAG_RULE_BT0337_PATTERN3, EAWAG_RULE_BT0337_PATTERN4, EAWAG_RULE_BT0337_PATTERN5,
//		EAWAG_RULE_BT0337_PATTERN6, EAWAG_RULE_BT0352_PATTERN1, EAWAG_RULE_BT0352_PATTERN2, EAWAG_RULE_BT0352_PATTERN3,
//		EAWAG_RULE_BT0352_PATTERN4, EAWAG_RULE_BT0352_PATTERN5, EAWAG_RULE_BT0267, EAWAG_RULE_BT0280,
//		EAWAG_RULE_BT0282, EAWAG_RULE_BT0322, EAWAG_RULE_BT0330_PATTERN1, EAWAG_RULE_BT0330_PATTERN2, EAWAG_RULE_BT0330_PATTERN3,
//		EAWAG_RULE_BT0330_PATTERN4, EAWAG_RULE_BT0330_PATTERN5, EAWAG_RULE_BT0330_PATTERN6, EAWAG_RULE_BT0339,
//		EAWAG_RULE_BT0342, EAWAG_RULE_BT0345,
//		EAWAG_RULE_BT0348_PATTERN3, EAWAG_RULE_BT0348_PATTERN4, EAWAG_RULE_BT0348_PATTERN5, EAWAG_RULE_BT0348_PATTERN6,
//		EAWAG_RULE_BT0348_PATTERN7, EAWAG_RULE_BT0414, EAWAG_RULE_BT0358, EAWAG_RULE_BT0378_PATTERN1, EAWAG_RULE_BT0378_PATTERN2,
//		EAWAG_RULE_BT0387, EAWAG_RULE_BT0390, EAWAG_RULE_BT0392,  EAWAG_RULE_BT0393,  EAWAG_RULE_BT0394, EAWAG_RULE_BT0403,
//		EAWAG_RULE_BT0404, EAWAG_RULE_BT0420_PATTERN1, EAWAG_RULE_BT0420_PATTERN2, EAWAG_RULE_BT0425_PATTERN1,
//		EAWAG_RULE_BT0425_PATTERN2, EAWAG_RULE_BT0429, EAWAG_RULE_BT0431, EAWAG_RULE_BT0438, EAWAG_RULE_BT0440,
//		EAWAG_RULE_BT0288, EAWAG_RULE_BT0327,
//
//
//		/*
//		 * Deglycosylation
//		 */
//		ALKYL_OH_DEGLYCOSYLATION, ACYL_O_DEGLYCOSYLATION, HYDROXAMIC_O_DEGLYCOSYLATION, HYDROXYLAMINE_O_DEGLYCOSYLATION,
//		PHENOL_O_DEGLYCOSYLATION, DEGLYCOSYLATION_PATTERN1, DEGLYCOSYLATION_PATTERN2, DEGLYCOSYLATION_PATTERN3, DEGLYCOSYLATION_PATTERN4,
//		DEGLYCOSYLATION_PATTERN5, DEGLYCOSYLATION_PATTERN6, DEGLYCOSYLATION_PATTERN7, DEGLYCOSYLATION_PATTERN8, DEGLYCOSYLATION_PATTERN9,
//		DEGLYCOSYLATION_PATTERN10, DEGLYCOSYLATION_PATTERN11, DEGLYCOSYLATION_PATTERN12, DEGLYCOSYLATION_PATTERN13, DEGLYCOSYLATION_PATTERN15,
//		DEGLYCOSYLATION_PATTERN16, DEGLYCOSYLATION_PATTERN17, DEGLYCOSYLATION_PATTERN18, DEGLYCOSYLATION_PATTERN19, DEGLYCOSYLATION_PATTERN20,
//		DEGLYCOSYLATION_PATTERN21, DEGLYCOSYLATION_PATTERN22, DEGLYCOSYLATION_PATTERN23, DEGLYCOSYLATION_PATTERN24, DEGLYCOSYLATION_PATTERN25,
//		DEGLYCOSYLATION_PATTERN26, DEGLYCOSYLATION_PATTERN27, DEGLYCOSYLATION_PATTERN28, DEGLYCOSYLATION_PATTERN29, DEGLYCOSYLATION_PATTERN30,
//		DEGLYCOSYLATION_PATTERN31, DEGLYCOSYLATION_PATTERN32, DEGLYCOSYLATION_PATTERN33, DEGLYCOSYLATION_PATTERN34, DEGLYCOSYLATION_PATTERN35,
//		DEGLYCOSYLATION_PATTERN36, DEGLYCOSYLATION_PATTERN37, DEGLYCOSYLATION_PATTERN38, DEGLYCOSYLATION_PATTERN39, DEGLYCOSYLATION_PATTERN40,
//		DEGLYCOSYLATION_PATTERN41, DEGLYCOSYLATION_PATTERN42, DEGLYCOSYLATION_PATTERN43,
//
//		 /**
//		  * Miscellaneous
//		  */
//
//
////		ADD SMARTS FOR THOSE REATIONS
//		// PMID: 12975333 DOI: 10.1124/dmd.31.10.1240
//		ISOXAZOLE_RING_OPENING,
//
//		REDUCTION_OF_ALPHA_BETA_UNSATURATED_COMPOUNDS_PATTERN2, REDUCTION_OF_ALPHA_BETA_UNSATURATED_COMPOUNDS_PATTERN3,
//		OXIDATION_OF_SEC_ALICYCLIC_ALCOHOL,
//
//		 ARYL_ALCOHOL_DEHYDROGENATION, _20_ALPHA_HYDROXYSTEROID_DEHYDROGENATION, _21_HYDROXYSTEROID_DEHYDROGENATION, ARYL_ALCOHOL_OXIDATION,
//
//		OXIDATIVE_N_DEARYLATION_1, OXIDATIVE_N_DEARYLATION_2, THIOCARBAMIC_ACID_S_METHYLATION, DITHIOCARBAMIC_ACID_S_METHYLATION,
//		ANILINE_P_HYDROXYLATION, P_HYDROXIANILINE_OXIDATION, O_AMINOPHENOL_OXIDATION, P_METHYL_HYDROXYLATION, PHENOLIC_P_DEHYDROXYLATION,
//		CMP_N_ACYLNEURAMINATE_HYDROLYSIS, ACETYLNEURAMINYL_HYDROLYSIS_PATTERN1, ACETYLNEURAMINYL_HYDROLYSIS_PATTERN2, ACETYLNEURAMINYL_HYDROLYSIS_PATTERN3,
//		CHOLINE_LYSIS_TO_TRIMETHYLAMINE,
//		_2_3_ENOYL_COA_HYDRATION
	}


//	public static LinkedHashMap<String, String>			setOfSMIRKS;
//	static {
//		setOfSMIRKS = new LinkedHashMap<String, String>();
//
//		/**
//		 * 	Standardization reactions
//		 */
//		setOfSMIRKS.put("AZIDE_STANDARDIZATION","[#7;A;X2-:1][N;X2+:2]#[N;X1:3]>>[#7:1]=[N+:2]=[#7-:3]");
//		setOfSMIRKS.put("CARBOXAMIDE_STANDARDIZATION_PATTERN1","[H][#8;X2:3][#6;A;X3:2]([#6:1])=[#7;$([#7;X2]-[#6]),$([#7;X2H1]):4]>>[#6:1][#6;A;X3:2]([#7;A;$([#7;X3H1]-[#6]),$([#7;X3H2]):4])=[O;X1:3]");
//		setOfSMIRKS.put("CARBOXAMIDE_STANDARDIZATION_PATTERN2","[#6:1]-[#6;X3:2]([#8;A;X1-:3])=[#7;$([#7;X2]-[#6]),$([#7;X2H1]):4]>>[#6:1]-[#6;X3:2](-[#7;X3:4])=[#8;A;X1:3]");
//		setOfSMIRKS.put("DIAZO_STANDARDIZATION","[#6;A;X3-:1][N;X2+:2]#[N;X1:3]>>[#6;A:1]=[N+:2]=[#7-:3]");
//		setOfSMIRKS.put("DIAZONIUM_STANDARDIZATION","[#6]-[#7:1]=[#7+:2]>>[#6][N+:1]#[N:2]");
//		setOfSMIRKS.put("IMINIUM_STANDARDIZATION","[#6;A;X3+:1][#7;A;X3:2]>>[#6;A:1]=[#7+:2]");
//		setOfSMIRKS.put("ISOCYANATE_STANDARDIZATION","[H][#7:1][#6;A;X2H0;v3-:2]=[O:3]>>[#7;v3:1]=[C;X2;v4:2]=[O:3]");
//		setOfSMIRKS.put("NITRILIUM_STANDARDIZATION","[#6;A;X2+:1]=[#7;X2:2]>>[C:1]#[N+:2]");
//		setOfSMIRKS.put("NITRO_STANDARDIZATION","[O:3]=[N;X3+0,X3-:1]=[OX1-,OX1+0:2]>>[#8-:2]-[#7+:1]=[O:3]");
//		setOfSMIRKS.put("NITRO_STANDARDIZATION_1","[H][#8;A;X2:2][#7;A;X4H1,X3+,X3-:1]([#6])=[O;X1:3]>>[#6][#7;A;X3+:1]([#8;A;X1-:3])=[O:2]");
//		setOfSMIRKS.put("NITRONATE_STANDARDIZATION","[#8;X1-:1]-[#7;X3+:2](-[#8;X1-:3])=[#6;A:4]>>[H][#6;A:4][#7;X3+:2](-[#8;X1-:3])=[O;X1:1]");
//		setOfSMIRKS.put("NITROSO_STANDARDIZATION","[#6]-[#7H2+:1]-[#8;X1-:2]>>[#6]-[#7:1]=[O:2]");
//		setOfSMIRKS.put("PHOSPHONIC_STANDARDIZATION","[#6][P+:1]([#8;X2])([#8;X2])[#8-:2]>>[#6][P:1]([#8])([#8])=[O:2]");
//		setOfSMIRKS.put("PHOSPHORIC_STANDARDIZATION","[#8;X1-:1][P;X4:2](=[O;X1:3])([#8;X2:6]-[*,#1:7])[#8;X2:4]-[*,#1:5]>>[H][#8;X2:1][P;X4:2](=[O;X1:3])([#8;X2:6]-[*,#1:7])[#8;X2:4]-[*,#1:5]");
//		setOfSMIRKS.put("PHOSPHORIC_STANDARDIZATION_2","[#8;X1-:3][P;X4:2]([#8;X1-:4])(=[O;X1:5])[#8;X2:1]-[*,#1:6]>>[H][#8;X2:3][P;X4:2](=[O;X1:5])([#8;X2:4][H])[#8;X2:1]-[*,#1:6]");
//		setOfSMIRKS.put("PHOSPHONIUM_YLIDE_STANDARDIZATION","[#6][P-:1]([#6])([#6])[#6+:2]>>[#6][P:1]([#6])([#6])=[#6;A:2]");
//		setOfSMIRKS.put("SELENITE_STANDARDIZATION","[#8;X2][Se+:1]([#8;X2])[#8-:2]>>[#8][Se:1]([#8])=[O:2]");
//		setOfSMIRKS.put("SILICATE_STANDARDIZATION","[#8;X2]-[#14+:1](-[#8;X2])-[#8-:2]>>[#8]-[#14:1](-[#8])=[O:2]");
//		setOfSMIRKS.put("SULFINE_STANDARDIZATION","[#6]-[#6](-[#6])=[S+:1][#8-:2]>>[#6]-[#6](-[#6])=[S:1]=[O:2]");
//		setOfSMIRKS.put("SULFONE_STANDARDIZATION","[#6][S;X3+:1]([#6])[#8-:2]>>[#6][S:1]([#6])=[O:2]");
//		setOfSMIRKS.put("SULFONIUM_YLIDE_STANDARDIZATION","[#6][S-:1]([#6])[#6+:2]>>;[#6][S:1]([#6])=[#6;A:2]");
//		setOfSMIRKS.put("SULFOXIDE_STANDARDIZATION","[#6][S+:1]([#6])([#8-:2])=O>>[#6][S:1]([#6])(=[O:2])=O");
////		setOfSMIRKS.put("SULFOXONIUM_YLIDE_STANDARDIZATION","[#6][S+:1]([#6])([#8-:2])=[#6;A]>>[#6][S:1]([#6])(=[#6;A])=[O:2]");
//		setOfSMIRKS.put("TERTIARY_N_OXIDE_STANDARDIZATION","[#6]-[#7;X4:1]=[O:2]>>[#6]-[#7+:1]-[#8-:2]");
//		setOfSMIRKS.put("THIOUREA_STANDARDIZATION","[#7;X3:1]-[#6;X3:2](-[#16;H1X2:3])=[#7;X2:4]>>[#7;X3:1]-[#6;X3:2](-[#7;X3:4])=[S;X1:3]");
//		setOfSMIRKS.put("CARBAMIDOTHIOIC_ACID_TO_THIOUREA_STANDARDIZATION","[#7;X3:1]-[#6;X3:2](-[#16;H1X2:3])=[#7;X2:4]>>[#7;X3:1]-[#6;X3:2](-[#7;X3:4])=[S;X1:3]");
//		setOfSMIRKS.put("CARBAMIDIC_ACID_TO_UREA_STANDARDIZATION","[H][#8;X2:3]-[#6;X3:2](-[#7;X3:1])=[#7;X2:4]>>[H][#7;X3:4]-[#6;X3:2](-[#7;X3:1])=[O;X1:3]");
//		setOfSMIRKS.put("CARBOXYLIC_ACID_ANION_STANDARDIZATION","[#8;X1-:1]-[#6;X3:2](-[#6,#1:3])=[O;X1:4]>>[H][#8;X2:1]-[#6;X3:2](-[#6,#1:3])=[O;X1:4]");
//		setOfSMIRKS.put("SULFONIC_ACID_STANDARDIZATION","[#8;X1-:1][S;X4:2]([#6,#1;A:5])(=[O;X1:3])=[O;X1:4]>>[H][#8;X2:1][S;X4:2]([#6,#1;A:5])(=[O;X1:3])=[O;X1:4]");
////		setOfSMIRKS.put("COENZYME_A_STANDARDIZATION","");
//
//		setOfSMIRKS.put("ANTHOCYANIDIN_STANDARDIZATION_PATTERN1","[#6;R1:1]-1=[#6;R1:6]-[#6;R1:5]=[#6;R1:4](-[#6;R1:3]=[#6;R1:2]-1)-[#6;R1:7]1=[#6;R1:8]-[#6;R1:9]=[#6:10]-2-[#6:11]=[#6:12]-[#6:13]=[#6:14]-[#6:15]-2=[O+:16]1>>"
//				+ "[#6;R1:1]-1=[#6;R1:6]-[#6;R1:5]=[#6;R1:4](-[#6;R1:3]=[#6;R1:2]-1)-[#6;R1:7]-1=[O+:16][#6:15]-2=[#6:10](-[#6:11]=[#6:12]-[#6:13]=[#6:14]-2)-[#6;R1:9]=[#6;R1:8]-1");
//
//
//		/**
//		 * CYP450 reactions
//		 */
//
//
//		/**
//		 * 	Phase II reactions
//		 */
//
//		/**
//		 * 	Human Gut Metabolism Reactions
//		 */
//
//		/**
//		 * EC-Based Reactions
//		 */
//
//	}
//
//	public static LinkedHashMap<String, ArrayList<String>>	setOfReactantSMARTS;
//	static {
//		setOfReactantSMARTS = new LinkedHashMap<String, ArrayList<String>>();
//
//		/***
//		 *  Standardization reactions
//		 ***/
//		setOfReactantSMARTS.put("AZIDE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#7;A;X2-][N;X2+]#[N;X1]")));
//		setOfReactantSMARTS.put("CARBOXAMIDE_STANDARDIZATION_PATTERN1",
//				new ArrayList<String>(Arrays.asList("[#6]-[#6;X3]([#8;A;X2H1])=[#7;$([#7;X2]-[#6]),$([#7;X2H1])]")));		
//		setOfReactantSMARTS.put("CARBOXAMIDE_STANDARDIZATION_PATTERN2",
//				new ArrayList<String>(Arrays.asList("[#6]-[#6;X3]([#8;A;X1-])=[#7;$([#7;X2]-[#6]),$([#7;X2H1])]")));
//		setOfReactantSMARTS.put("DIAZO_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6;X3-][N;X2+]#[N;X1]")));
//		setOfReactantSMARTS.put("DIAZONIUM_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6]-[#7]=[#7+]")));
//		setOfReactantSMARTS.put("IMINIUM_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6;A;X3+][#7;A;X3]")));
//		setOfReactantSMARTS.put("ISOCYANATE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[H][#7][#6;A;X2H0;v3-]=O")));
//		setOfReactantSMARTS.put("NITRILIUM_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6;A;X2+]=[#7;X2]")));
//		setOfReactantSMARTS.put("NITRO_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("O=[N;X3+0,X3-]=[OX1-,OX1+0]")));
//		setOfReactantSMARTS.put("NITRO_STANDARDIZATION_1",
//				new ArrayList<String>(Arrays.asList("[H][#8;A;X2][#7;A;X4H1,X3+,X3-]([#6])=[O;X1]")));
//		setOfReactantSMARTS.put("NITRONATE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X1-]-[#7;X3+](-[#8;X1-])=[#6;A]")));
//		setOfReactantSMARTS.put("NITROSO_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6]-[#7H2+]-[#8;X1-]")));
//		setOfReactantSMARTS.put("PHOSPHONIC_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6][P+]([#8;X2])([#8;X2])[#8-]")));
//		setOfReactantSMARTS.put("PHOSPHORIC_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X1-][P;X4](=[O;X1])([#8;X2]-[*,#1])[#8;X2]-[*,#1]")));
//		setOfReactantSMARTS.put("PHOSPHORIC_STANDARDIZATION_2",
//				new ArrayList<String>(Arrays.asList("[#8;X1-][P;X4]([#8;X1-])(=[O;X1])[#8;X2]-[*,#1]")));
//		setOfReactantSMARTS.put("PHOSPHONIUM_YLIDE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6][P-]([#6])([#6])[#6+]")));
//		setOfReactantSMARTS.put("SELENITE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X2][Se+]([#8;X2])[#8-]")));
//		setOfReactantSMARTS.put("SILICATE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X2]-[#14+](-[#8;X2])-[#8-]")));
//		setOfReactantSMARTS.put("SULFINE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6]-[#6](-[#6])=[S+][#8-]")));
//		setOfReactantSMARTS.put("SULFONE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6][S;X3+]([#6])[#8-]")));
//		setOfReactantSMARTS.put("SULFONIUM_YLIDE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6][S-]([#6])[#6+]")));
//		setOfReactantSMARTS.put("SULFOXIDE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6][S+]([#6])([#8-])=O")));
////		setOfReactantSMARTS.put("SULFOXONIUM_YLIDE_STANDARDIZATION",
////				new ArrayList<String>(Arrays.asList("[#6][S+]([#6])([#8-])=[#6;A]")));
//		setOfReactantSMARTS.put("TERTIARY_N_OXIDE_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#6]-[#7;X4]=O")));
//		setOfReactantSMARTS.put("THIOUREA_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#7;X3]-[#6;X3](-[#16;H1X2])=[#7;X2]")));
//		setOfReactantSMARTS.put("CARBAMIDOTHIOIC_ACID_TO_THIOUREA_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#7;X3]-[#6;X3](-[#16;H1X2])=[#7;X2]")));
//		setOfReactantSMARTS.put("CARBAMIDIC_ACID_TO_UREA_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#7;X3]-[#6;X3](-[#8;H1X2])=[#7;X2]")));
//		setOfReactantSMARTS.put("CARBOXYLIC_ACID_ANION_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X1-]-[#6;X3](-[#6,#1])=[O;X1]")));
//		setOfReactantSMARTS.put("SULFONIC_ACID_STANDARDIZATION",
//				new ArrayList<String>(Arrays.asList("[#8;X1-][S;X4]([#6,#1;A])(=[O;X1])=[O;X1]")));
//		setOfReactantSMARTS.put("ANTHOCYANIDIN_STANDARDIZATION_PATTERN1",
//				new ArrayList<String>(Arrays.asList("[#6;R1]=,:1[#6;R1]=,:[#6;R1][#6;R1](=,:[#6;R1][#6;R1]=,:1)-[#6;R1]1=,:[#6;R1][#6;R1]=,:[#6]2[#6]=,:[#6][#6]=,:[#6][#6]2=,:[#8+]1")));
//		/**
//		 * CYP450 reactions
//		 */
//
//		/**
//		 * 	Phase II reactions
//		 */
//
//		/**
//		 * 	Human Gut Metabolism Reactions
//		 */
//
//		/**
//		 * EC-Based Reactions
//		 */
//		/**
//		 * CYP450 reactions
//		 */
//
//		/**
//		 * 	Phase II reactions
//		 */
//
//		/**
//		 * 	Human Gut Metabolism Reactions
//		 */
//
//		/**
//		 * EC-Based Reactions
//		 */
//
//	}


}
